// /////////////////////////////////////////////////////////////////////////
// C++ code automatically generated by hif2sc
// Part of HIFSuite - Version 
// Site: www.hifsuite.com - Contact: hifsuite@edalab.it
//
// HIFSuite copyright: EDALab s.r.l. - Networked Embedded Systems
// Site: www.edalab.it - Contact: info@edalab.it
// /////////////////////////////////////////////////////////////////////////


#include "../../inc/muffin/FaultNode.hpp"


namespace muffin {


FaultNode::FaultNode( uint64_t _instance, uint64_t _number ) :
    next(nullptr),
    prev(nullptr),
    instance(0ULL),
    number(0ULL)
{
    instance = _instance;
    number = _number;
}


FaultNode::~FaultNode()
{}




} // end namespace muffin

