/* Generated by Yosys 0.47+149 (git sha1 384c19119, clang++ 18.1.8 -fPIC -O3) */

module spec1(clock, a_1, b_1, c_0, e_0, d_0);
input clock;
wire clock;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  input a_1;
  wire a_1;
  input b_1;
  wire b_1;
  input c_0;
  wire c_0;
  input clock;
  wire clock;
  output d_0;
  reg d_0 = 1'h0;
  output e_0;
  wire e_0;
  assign _00_ = c_0 & d_0;
  assign _01_ = _06_ & _00_;
  assign _03_ = _09_ & _02_;
  assign _06_ = a_1 & b_1;
  assign _07_ = c_0 & _05_;
  assign _08_ = _06_ & _07_;
  always @(posedge clock)
    d_0 <= _04_;
  assign _02_ = ~_01_;
  assign _04_ = ~_03_;
  assign _05_ = ~d_0;
  assign _09_ = ~_08_;
  assign e_0 = d_0;
endmodule
