// /////////////////////////////////////////////////////////////////////////
// C++ code automatically generated by hif2sc
// Part of HIFSuite - Version 
// Site: www.hifsuite.com - Contact: hifsuite@edalab.it
//
// HIFSuite copyright: EDALab s.r.l. - Networked Embedded Systems
// Site: www.edalab.it - Contact: info@edalab.it
// /////////////////////////////////////////////////////////////////////////


#ifndef SPEC1_HH
#define SPEC1_HH

#include <cmath>
#include <cstddef>
#include <stdint.h>
#include "hif_globals.hpp"
#include "muffin/FaultNode.hpp"
#include "muffin/muffin_dataTypes.hpp"

class spec1
{

public:

    muffin::FaultNode hif_fault_node;
    bool b_2_old;
    bool a_2_old;
    bool clock_old;
    struct spec1_iostruct{
        bool * clock;
        bool * a_2;
        bool * b_2;
        bool * c_2;

        spec1_iostruct():
            clock(nullptr),
            a_2(nullptr),
            b_2(nullptr),
            c_2(nullptr)
        {}

        spec1_iostruct( bool * clock_1, bool * a_2_0, bool * b_2_0, bool * c_2_0
             ):
            clock(clock_1),
            a_2(a_2_0),
            b_2(b_2_0),
            c_2(c_2_0)
        {}

        ~spec1_iostruct()
        {}

        bool operator == (const spec1_iostruct & other) const
        {
            if (clock != other.clock) return false;
            if (a_2 != other.a_2) return false;
            if (b_2 != other.b_2) return false;
            if (c_2 != other.c_2) return false;
            return true;
        }
    };
    spec1_iostruct hif_a2t_data;
    bool _00_;
    bool _01_;
    bool _02_;
    bool _03_;
    bool _04_;
    bool _05_;
    bool _06_;
    bool _07_;
    bool _08_;
    bool _09_;
    bool _10_;
    bool _11_;
    bool _12_;
    bool _13_;
    bool _14_;
    bool _15_;
    bool _16_;
    bool _17_;
    bool _18_;
    bool _19_;
    bool _20_;
    bool _21_;
    bool _22_;
    bool _23_;
    bool _24_;
    bool _25_;
    bool _26_;
    bool _27_;
    bool _28_;
    bool _29_;
    bool _30_;
    bool _31_;
    bool _32_;
    bool _33_;
    bool _34_;
    bool _35_;
    bool _36_;
    bool _37_;

    void hif_cone__24__1();


    void hif_cone__29__0();

    spec1();


    ~spec1();


    bool _37__new;
    bool process_in_queue;
    bool flag_process_1_process_2_executed;
    bool flag_pos_clock;

    void process_1_process_2();


    void update_input_queue( bool synch_phase = true );


    void update_event_queue();


    void flag_elaboration();


    void start_of_simulation();


    void initialize();


private:

    spec1( const spec1 & );
    const spec1& operator= ( const spec1 & );


};


#endif

