// /////////////////////////////////////////////////////////////////////////
// C++ code automatically generated by hif2sc
// Part of HIFSuite - Version 
// Site: www.hifsuite.com - Contact: hifsuite@edalab.it
//
// HIFSuite copyright: EDALab s.r.l. - Networked Embedded Systems
// Site: www.edalab.it - Contact: info@edalab.it
// /////////////////////////////////////////////////////////////////////////


#ifndef SPEC2_HH
#define SPEC2_HH

#include <cmath>
#include <cstddef>
#include <stdint.h>
#include "hif_globals.hpp"
#include "muffin/FaultNode.hpp"
#include "muffin/muffin_dataTypes.hpp"

class spec2
{

public:

    muffin::FaultNode hif_fault_node;
    bool b_3_old;
    bool a_3_old;
    bool clock_old;
    struct spec2_iostruct{
        bool * clock;
        bool * a_3;
        bool * b_3;
        bool * c_3;

        spec2_iostruct():
            clock(nullptr),
            a_3(nullptr),
            b_3(nullptr),
            c_3(nullptr)
        {}

        spec2_iostruct( bool * clock_2, bool * a_3_0, bool * b_3_0, bool * c_3_0
             ):
            clock(clock_2),
            a_3(a_3_0),
            b_3(b_3_0),
            c_3(c_3_0)
        {}

        ~spec2_iostruct()
        {}

        bool operator == (const spec2_iostruct & other) const
        {
            if (clock != other.clock) return false;
            if (a_3 != other.a_3) return false;
            if (b_3 != other.b_3) return false;
            if (c_3 != other.c_3) return false;
            return true;
        }
    };
    spec2_iostruct hif_a2t_data;
    bool _00_;
    bool _01_;
    bool _02_;
    bool _03_;
    bool _04_;
    bool _05_;
    bool _06_;
    bool _07_;
    bool _08_;
    bool _09_;
    bool _10_;
    bool _11_;
    bool _12_;
    bool _13_;
    bool _14_;
    bool _15_;
    bool _16_;
    bool _17_;
    bool _18_;
    bool _19_;
    bool _20_;
    bool _21_;
    bool _22_;
    bool _23_;
    bool _24_;
    bool _25_;
    bool _26_;
    bool _27_;
    bool _28_;
    bool _29_;
    bool _30_;
    bool _31_;
    bool _32_;
    bool _33_;
    bool _34_;
    bool _35_;
    bool _36_;
    bool _37_;

    void hif_cone__24_();


    void hif_cone__29_();

    spec2();


    ~spec2();


    bool _37__new;
    bool process_in_queue;
    bool flag_process_3_process_4_executed;
    bool flag_pos_clock;

    void process_3_process_4();


    void update_input_queue( bool synch_phase = true );


    void update_event_queue();


    void flag_elaboration();


    void start_of_simulation();


    void initialize();


private:

    spec2( const spec2 & );
    const spec2& operator= ( const spec2 & );


};


#endif

