/* Generated by Yosys 0.47+149 (git sha1 384c19119, clang++ 18.1.8 -fPIC -O3) */

module spec4(clk, a_4, a_0, c_0, f_0, d_0, e_0);
input clk;
wire clk;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  input a_0;
  wire a_0;
  input a_4;
  wire a_4;
  input c_0;
  wire c_0;
  input clk;
  wire clk;
  output d_0;
  reg d_0 = 1'h0;
  output e_0;
  wire e_0;
  output f_0;
  wire f_0;
  assign _00_ = c_0 & d_0;
  assign _01_ = _06_ & _00_;
  assign _03_ = _09_ & _02_;
  assign _06_ = a_0 & a_4;
  assign _07_ = c_0 & _05_;
  assign _08_ = _06_ & _07_;
  always @(posedge clk)
    d_0 <= _04_;
  assign _02_ = ~_01_;
  assign _04_ = ~_03_;
  assign _05_ = ~d_0;
  assign _09_ = ~_08_;
  assign e_0 = d_0;
  assign f_0 = d_0;
endmodule
