/* Generated by Yosys 0.47+149 (git sha1 384c19119, clang++ 18.1.8 -fPIC -O3) */

module spec3(clk, a_3, b_3, c_3, d_3);
input clk;
wire clk;
  wire _0_;
  wire _1_;
  wire _2_;
  input a_3;
  wire a_3;
  input b_3;
  wire b_3;
  output c_3;
  wire c_3;
  output d_3;
  wire d_3;
  assign _2_ = _0_ & _1_;
  assign d_3 = c_3;
  assign _0_ = a_3;
  assign _1_ = b_3;
  assign c_3 = _2_;
endmodule
