/* Generated by Yosys 0.47+149 (git sha1 384c19119, clang++ 18.1.8 -fPIC -O3) */

module spec1(clk, a_1, b_1, c_1, d_1);
input clk;
wire clk;
  wire _0_;
  wire _1_;
  wire _2_;
  input a_1;
  wire a_1;
  input b_1;
  wire b_1;
  output c_1;
  wire c_1;
  output d_1;
  wire d_1;
  assign _2_ = _0_ & _1_;
  assign d_1 = c_1;
  assign _0_ = a_1;
  assign _1_ = b_1;
  assign c_1 = _2_;
endmodule
