/* Generated by Yosys 0.47+149 (git sha1 384c19119, clang++ 18.1.8 -fPIC -O3) */

module spec0(clk, a_0, b_0, c_0, d_0);
input clk;
wire clk;
  wire _0_;
  wire _1_;
  wire _2_;
  input a_0;
  wire a_0;
  input b_0;
  wire b_0;
  output c_0;
  wire c_0;
  output d_0;
  wire d_0;
  assign _2_ = _0_ & _1_;
  assign d_0 = c_0;
  assign _0_ = a_0;
  assign _1_ = b_0;
  assign c_0 = _2_;
endmodule
