/* Generated by Yosys 0.47+149 (git sha1 384c19119, clang++ 18.1.8 -fPIC -O3) */

module spec5(clk, a_5, b_5, c_5, d_5);
input clk;
wire clk;
  wire _0_;
  wire _1_;
  wire _2_;
  input a_5;
  wire a_5;
  input b_5;
  wire b_5;
  output c_5;
  wire c_5;
  output d_5;
  wire d_5;
  assign _2_ = _0_ & _1_;
  assign d_5 = c_5;
  assign _0_ = a_5;
  assign _1_ = b_5;
  assign c_5 = _2_;
endmodule
