/* Generated by Yosys 0.47+149 (git sha1 384c19119, clang++ 18.1.8 -fPIC -O3) */

module spec1(clock, a_1, b_1, c_1);
input clock;
wire clock;
  input a_1;
  wire a_1;
  input b_1;
  wire b_1;
  output c_1;
  wire c_1;
  assign c_1 = ~1'h0;
endmodule
