/* Generated by Yosys 0.47+149 (git sha1 384c19119, clang++ 18.1.8 -fPIC -O3) */

module spec3(clock, a_3, b_3, c_3);
input clock;
wire clock;
  input a_3;
  wire a_3;
  input b_3;
  wire b_3;
  output c_3;
  wire c_3;
  assign c_3 = ~1'h0;
endmodule
