// /////////////////////////////////////////////////////////////////////////
// C++ code automatically generated by hif2sc
// Part of HIFSuite - Version 
// Site: www.hifsuite.com - Contact: hifsuite@edalab.it
//
// HIFSuite copyright: EDALab s.r.l. - Networked Embedded Systems
// Site: www.edalab.it - Contact: info@edalab.it
// /////////////////////////////////////////////////////////////////////////


#ifndef FAULTNODE_HH
#define FAULTNODE_HH

#include <cmath>
#include <cstddef>
#include <stdint.h>
#include "muffin_dataTypes.hpp"

namespace muffin {

class FaultNode
{

public:

    FaultNode * next;
    FaultNode * prev;
    uint64_t instance;
    uint64_t number;
    FaultNode( uint64_t _instance = 0ULL, uint64_t _number = 0ULL );


    ~FaultNode();




private:

    FaultNode( const FaultNode & );
    const FaultNode& operator= ( const FaultNode & );


};

} // end namespace muffin


#endif

