/* Generated by Yosys 0.47+149 (git sha1 384c19119, clang++ 18.1.8 -fPIC -O3) */

module spec8(clk, a_8, b_8, c_8);
input clk;
wire clk;
  wire _0_;
  wire _1_;
  wire _2_;
  input a_8;
  wire a_8;
  input b_8;
  wire b_8;
  output c_8;
  wire c_8;
  assign _2_ = _0_ & _1_;
  assign _0_ = a_8;
  assign _1_ = b_8;
  assign c_8 = _2_;
endmodule
