/* Generated by Yosys 0.47+149 (git sha1 384c19119, clang++ 18.1.8 -fPIC -O3) */

module spec6(clk, a_6, b_6, c_6);
input clk;
wire clk;
  wire _0_;
  wire _1_;
  wire _2_;
  input a_6;
  wire a_6;
  input b_6;
  wire b_6;
  output c_6;
  wire c_6;
  assign _2_ = _0_ & _1_;
  assign _0_ = a_6;
  assign _1_ = b_6;
  assign c_6 = _2_;
endmodule
