/* Generated by Yosys 0.47+149 (git sha1 384c19119, clang++ 18.1.8 -fPIC -O3) */

module spec7(clk, a_7, b_7, c_7);
input clk;
wire clk;
  wire _0_;
  wire _1_;
  wire _2_;
  input a_7;
  wire a_7;
  input b_7;
  wire b_7;
  output c_7;
  wire c_7;
  assign _2_ = _0_ & _1_;
  assign _0_ = a_7;
  assign _1_ = b_7;
  assign c_7 = _2_;
endmodule
