/* Generated by Yosys 0.47+149 (git sha1 384c19119, clang++ 18.1.8 -fPIC -O3) */

module spec2(clk, a_2, b_2, c_2);
input clk;
wire clk;
  wire _0_;
  wire _1_;
  wire _2_;
  input a_2;
  wire a_2;
  input b_2;
  wire b_2;
  output c_2;
  wire c_2;
  assign _2_ = _0_ & _1_;
  assign _0_ = a_2;
  assign _1_ = b_2;
  assign c_2 = _2_;
endmodule
