/* Generated by Yosys 0.47+149 (git sha1 384c19119, clang++ 18.1.8 -fPIC -O3) */

module spec4(clk, a_4, b_4, c_4);
input clk;
wire clk;
  wire _0_;
  wire _1_;
  wire _2_;
  input a_4;
  wire a_4;
  input b_4;
  wire b_4;
  output c_4;
  wire c_4;
  assign _2_ = _0_ & _1_;
  assign _0_ = a_4;
  assign _1_ = b_4;
  assign c_4 = _2_;
endmodule
