/* Generated by Yosys 0.47+149 (git sha1 384c19119, clang++ 18.1.8 -fPIC -O3) */

module spec9(clk, a_9, b_9, c_9);
input clk;
wire clk;
  wire _0_;
  wire _1_;
  wire _2_;
  input a_9;
  wire a_9;
  input b_9;
  wire b_9;
  output c_9;
  wire c_9;
  assign _2_ = _0_ & _1_;
  assign _0_ = a_9;
  assign _1_ = b_9;
  assign c_9 = _2_;
endmodule
