// /////////////////////////////////////////////////////////////////////////
// C++ code automatically generated by hif2sc
// Part of HIFSuite - Version 
// Site: www.hifsuite.com - Contact: hifsuite@edalab.it
//
// HIFSuite copyright: EDALab s.r.l. - Networked Embedded Systems
// Site: www.edalab.it - Contact: info@edalab.it
// /////////////////////////////////////////////////////////////////////////


#ifndef SPEC0_HH
#define SPEC0_HH

#include <cmath>
#include <cstddef>
#include <stdint.h>
#include "hif_globals.hpp"
#include "muffin/FaultNode.hpp"
#include "muffin/muffin_dataTypes.hpp"

class spec0
{

public:

    muffin::FaultNode hif_fault_node;
    bool b_0_old;
    bool a_0_old;
    bool clock_old;
    struct spec0_iostruct{
        bool * clock;
        bool * a_0;
        bool * b_0;
        bool * c_0;

        spec0_iostruct():
            clock(nullptr),
            a_0(nullptr),
            b_0(nullptr),
            c_0(nullptr)
        {}

        spec0_iostruct( bool * clock_0, bool * a_0_0, bool * b_0_0, bool * c_0_0
             ):
            clock(clock_0),
            a_0(a_0_0),
            b_0(b_0_0),
            c_0(c_0_0)
        {}

        ~spec0_iostruct()
        {}

        bool operator == (const spec0_iostruct & other) const
        {
            if (clock != other.clock) return false;
            if (a_0 != other.a_0) return false;
            if (b_0 != other.b_0) return false;
            if (c_0 != other.c_0) return false;
            return true;
        }
    };
    spec0_iostruct hif_a2t_data;
    spec0();


    ~spec0();


    bool process_in_queue;

    void update_input_queue( bool synch_phase = true );


    void update_event_queue();


    void flag_elaboration();


    void start_of_simulation();


    void initialize();


private:

    spec0( const spec0 & );
    const spec0& operator= ( const spec0 & );


};


#endif

