/* Generated by Yosys 0.47+149 (git sha1 384c19119, clang++ 18.1.8 -fPIC -O3) */

module spec4(clk, a_4, b_4, c_0, d_4, d_1, e_3);
input clk;
wire clk;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  input a_4;
  wire a_4;
  input b_4;
  wire b_4;
  input c_0;
  wire c_0;
  input clk;
  wire clk;
  output d_1;
  reg d_1 = 1'h0;
  output d_4;
  wire d_4;
  output e_3;
  wire e_3;
  assign _00_ = c_0 & d_1;
  assign _01_ = _06_ & _00_;
  assign _03_ = _09_ & _02_;
  assign _06_ = a_4 & b_4;
  assign _07_ = c_0 & _05_;
  assign _08_ = _06_ & _07_;
  always @(posedge clk)
    d_1 <= _04_;
  assign _02_ = ~_01_;
  assign _04_ = ~_03_;
  assign _05_ = ~d_1;
  assign _09_ = ~_08_;
  assign d_4 = d_1;
  assign e_3 = d_1;
endmodule
