/* Generated by Yosys 0.47+149 (git sha1 384c19119, clang++ 18.1.8 -fPIC -O3) */

module spec3(clk, a_3, b_3, c_1, e_0, e_3, f_0);
input clk;
wire clk;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  input a_3;
  wire a_3;
  input b_3;
  wire b_3;
  input c_1;
  wire c_1;
  input clk;
  wire clk;
  output e_0;
  reg e_0 = 1'h0;
  output e_3;
  wire e_3;
  output f_0;
  wire f_0;
  assign _00_ = c_1 & e_0;
  assign _01_ = _06_ & _00_;
  assign _03_ = _09_ & _02_;
  assign _06_ = a_3 & b_3;
  assign _07_ = c_1 & _05_;
  assign _08_ = _06_ & _07_;
  always @(posedge clk)
    e_0 <= _04_;
  assign _02_ = ~_01_;
  assign _04_ = ~_03_;
  assign _05_ = ~e_0;
  assign _09_ = ~_08_;
  assign e_3 = e_0;
  assign f_0 = e_0;
endmodule
