/* Generated by Yosys 0.47+149 (git sha1 384c19119, clang++ 18.1.8 -fPIC -O3) */

module spec3(clk, a_3, b_2, c_3, d_3, e_2, e_0);
input clk;
wire clk;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  input a_3;
  wire a_3;
  input b_2;
  wire b_2;
  input c_3;
  wire c_3;
  input clk;
  wire clk;
  output d_3;
  reg d_3 = 1'h0;
  output e_0;
  wire e_0;
  output e_2;
  wire e_2;
  assign _00_ = c_3 & d_3;
  assign _01_ = _06_ & _00_;
  assign _03_ = _09_ & _02_;
  assign _06_ = a_3 & b_2;
  assign _07_ = c_3 & _05_;
  assign _08_ = _06_ & _07_;
  always @(posedge clk)
    d_3 <= _04_;
  assign _02_ = ~_01_;
  assign _04_ = ~_03_;
  assign _05_ = ~d_3;
  assign _09_ = ~_08_;
  assign e_0 = d_3;
  assign e_2 = d_3;
endmodule
