/* Generated by Yosys 0.47+149 (git sha1 384c19119, clang++ 18.1.8 -fPIC -O3) */

module spec4(clk, c_0, b_4, c_4, e_0, e_4, d_0);
input clk;
wire clk;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  input b_4;
  wire b_4;
  input c_0;
  wire c_0;
  input c_4;
  wire c_4;
  input clk;
  wire clk;
  output d_0;
  reg d_0 = 1'h0;
  output e_0;
  wire e_0;
  output e_4;
  wire e_4;
  assign _00_ = c_4 & d_0;
  assign _01_ = _06_ & _00_;
  assign _03_ = _09_ & _02_;
  assign _06_ = b_4 & c_0;
  assign _07_ = c_4 & _05_;
  assign _08_ = _06_ & _07_;
  always @(posedge clk)
    d_0 <= _04_;
  assign _02_ = ~_01_;
  assign _04_ = ~_03_;
  assign _05_ = ~d_0;
  assign _09_ = ~_08_;
  assign e_0 = d_0;
  assign e_4 = d_0;
endmodule
