/* Generated by Yosys 0.47+149 (git sha1 384c19119, clang++ 18.1.8 -fPIC -O3) */

module spec2(clk, a_1, b_2, c_2, f_0, e_2, e_0);
input clk;
wire clk;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  input a_1;
  wire a_1;
  input b_2;
  wire b_2;
  input c_2;
  wire c_2;
  input clk;
  wire clk;
  output e_0;
  reg e_0 = 1'h0;
  output e_2;
  wire e_2;
  output f_0;
  wire f_0;
  assign _00_ = c_2 & e_0;
  assign _01_ = _06_ & _00_;
  assign _03_ = _09_ & _02_;
  assign _06_ = a_1 & b_2;
  assign _07_ = c_2 & _05_;
  assign _08_ = _06_ & _07_;
  always @(posedge clk)
    e_0 <= _04_;
  assign _02_ = ~_01_;
  assign _04_ = ~_03_;
  assign _05_ = ~e_0;
  assign _09_ = ~_08_;
  assign e_2 = e_0;
  assign f_0 = e_0;
endmodule
