// /////////////////////////////////////////////////////////////////////////
// C++ code automatically generated by hif2sc
// Part of HIFSuite - Version 
// Site: www.hifsuite.com - Contact: hifsuite@edalab.it
//
// HIFSuite copyright: EDALab s.r.l. - Networked Embedded Systems
// Site: www.edalab.it - Contact: info@edalab.it
// /////////////////////////////////////////////////////////////////////////


#ifndef HIF_GLOBALS_HH
#define HIF_GLOBALS_HH

#include <cmath>
#include <cstddef>
#include <stdint.h>
#include "muffin/FaultNode.hpp"

extern muffin::FaultNode * hif_fault_list_root;


#endif

