// /////////////////////////////////////////////////////////////////////////
// C++ code automatically generated by hif2sc
// Part of HIFSuite - Version 
// Site: www.hifsuite.com - Contact: hifsuite@edalab.it
//
// HIFSuite copyright: EDALab s.r.l. - Networked Embedded Systems
// Site: www.edalab.it - Contact: info@edalab.it
// /////////////////////////////////////////////////////////////////////////


#ifndef TEST_HH
#define TEST_HH

#include <cmath>
#include <cstddef>
#include <stdint.h>
#include "hif_globals.hpp"
#include "muffin/FaultNode.hpp"
#include "muffin/muffin_dataTypes.hpp"

class test
{

public:

    muffin::FaultNode hif_fault_node;
    bool c_10_0_old;
    bool c_9_0_old;
    bool c_8_0_old;
    bool c_7_0_old;
    bool c_6_0_old;
    bool c_5_0_old;
    bool c_4_0_old;
    bool c_3_0_old;
    bool c_2_0_old;
    bool c_1_0_old;
    bool a_10_1_old;
    bool a_10_0_old;
    bool a_9_1_old;
    bool a_9_0_old;
    bool a_8_1_old;
    bool a_8_0_old;
    bool a_7_1_old;
    bool a_7_0_old;
    bool a_6_1_old;
    bool a_6_0_old;
    bool a_5_1_old;
    bool a_5_0_old;
    bool a_4_1_old;
    bool a_4_0_old;
    bool a_3_1_old;
    bool a_3_0_old;
    bool a_2_1_old;
    bool a_2_0_old;
    bool a_1_1_old;
    bool a_1_0_old;
    bool clock_old;
    struct test_iostruct{
        bool clock;
        bool a_1_0;
        bool a_1_1;
        bool a_2_0;
        bool a_2_1;
        bool a_3_0;
        bool a_3_1;
        bool a_4_0;
        bool a_4_1;
        bool a_5_0;
        bool a_5_1;
        bool a_6_0;
        bool a_6_1;
        bool a_7_0;
        bool a_7_1;
        bool a_8_0;
        bool a_8_1;
        bool a_9_0;
        bool a_9_1;
        bool a_10_0;
        bool a_10_1;
        bool c_1_0;
        bool c_1_1;
        bool c_2_0;
        bool c_2_1;
        bool c_3_0;
        bool c_3_1;
        bool c_4_0;
        bool c_4_1;
        bool c_5_0;
        bool c_5_1;
        bool c_6_0;
        bool c_6_1;
        bool c_7_0;
        bool c_7_1;
        bool c_8_0;
        bool c_8_1;
        bool c_9_0;
        bool c_9_1;
        bool c_10_0;
        bool c_10_1;

        test_iostruct():
            clock(false),
            a_1_0(false),
            a_1_1(false),
            a_2_0(false),
            a_2_1(false),
            a_3_0(false),
            a_3_1(false),
            a_4_0(false),
            a_4_1(false),
            a_5_0(false),
            a_5_1(false),
            a_6_0(false),
            a_6_1(false),
            a_7_0(false),
            a_7_1(false),
            a_8_0(false),
            a_8_1(false),
            a_9_0(false),
            a_9_1(false),
            a_10_0(false),
            a_10_1(false),
            c_1_0(false),
            c_1_1(false),
            c_2_0(false),
            c_2_1(false),
            c_3_0(false),
            c_3_1(false),
            c_4_0(false),
            c_4_1(false),
            c_5_0(false),
            c_5_1(false),
            c_6_0(false),
            c_6_1(false),
            c_7_0(false),
            c_7_1(false),
            c_8_0(false),
            c_8_1(false),
            c_9_0(false),
            c_9_1(false),
            c_10_0(false),
            c_10_1(false)
        {}

        test_iostruct( const bool clock_0, const bool a_1_0_0, const bool a_1_1_0,
             const bool a_2_0_0, const bool a_2_1_0, const bool a_3_0_0, const bool
             a_3_1_0, const bool a_4_0_0, const bool a_4_1_0, const bool a_5_0_0,
             const bool a_5_1_0, const bool a_6_0_0, const bool a_6_1_0, const bool
             a_7_0_0, const bool a_7_1_0, const bool a_8_0_0, const bool a_8_1_0,
             const bool a_9_0_0, const bool a_9_1_0, const bool a_10_0_0, const
             bool a_10_1_0, const bool c_1_0_0, const bool c_1_1_0, const bool c_2_0_0,
             const bool c_2_1_0, const bool c_3_0_0, const bool c_3_1_0, const bool
             c_4_0_0, const bool c_4_1_0, const bool c_5_0_0, const bool c_5_1_0,
             const bool c_6_0_0, const bool c_6_1_0, const bool c_7_0_0, const bool
             c_7_1_0, const bool c_8_0_0, const bool c_8_1_0, const bool c_9_0_0,
             const bool c_9_1_0, const bool c_10_0_0, const bool c_10_1_0 ):
            clock(clock_0),
            a_1_0(a_1_0_0),
            a_1_1(a_1_1_0),
            a_2_0(a_2_0_0),
            a_2_1(a_2_1_0),
            a_3_0(a_3_0_0),
            a_3_1(a_3_1_0),
            a_4_0(a_4_0_0),
            a_4_1(a_4_1_0),
            a_5_0(a_5_0_0),
            a_5_1(a_5_1_0),
            a_6_0(a_6_0_0),
            a_6_1(a_6_1_0),
            a_7_0(a_7_0_0),
            a_7_1(a_7_1_0),
            a_8_0(a_8_0_0),
            a_8_1(a_8_1_0),
            a_9_0(a_9_0_0),
            a_9_1(a_9_1_0),
            a_10_0(a_10_0_0),
            a_10_1(a_10_1_0),
            c_1_0(c_1_0_0),
            c_1_1(c_1_1_0),
            c_2_0(c_2_0_0),
            c_2_1(c_2_1_0),
            c_3_0(c_3_0_0),
            c_3_1(c_3_1_0),
            c_4_0(c_4_0_0),
            c_4_1(c_4_1_0),
            c_5_0(c_5_0_0),
            c_5_1(c_5_1_0),
            c_6_0(c_6_0_0),
            c_6_1(c_6_1_0),
            c_7_0(c_7_0_0),
            c_7_1(c_7_1_0),
            c_8_0(c_8_0_0),
            c_8_1(c_8_1_0),
            c_9_0(c_9_0_0),
            c_9_1(c_9_1_0),
            c_10_0(c_10_0_0),
            c_10_1(c_10_1_0)
        {}

        ~test_iostruct()
        {}

        bool operator == (const test_iostruct & other) const
        {
            if (clock != other.clock) return false;
            if (a_1_0 != other.a_1_0) return false;
            if (a_1_1 != other.a_1_1) return false;
            if (a_2_0 != other.a_2_0) return false;
            if (a_2_1 != other.a_2_1) return false;
            if (a_3_0 != other.a_3_0) return false;
            if (a_3_1 != other.a_3_1) return false;
            if (a_4_0 != other.a_4_0) return false;
            if (a_4_1 != other.a_4_1) return false;
            if (a_5_0 != other.a_5_0) return false;
            if (a_5_1 != other.a_5_1) return false;
            if (a_6_0 != other.a_6_0) return false;
            if (a_6_1 != other.a_6_1) return false;
            if (a_7_0 != other.a_7_0) return false;
            if (a_7_1 != other.a_7_1) return false;
            if (a_8_0 != other.a_8_0) return false;
            if (a_8_1 != other.a_8_1) return false;
            if (a_9_0 != other.a_9_0) return false;
            if (a_9_1 != other.a_9_1) return false;
            if (a_10_0 != other.a_10_0) return false;
            if (a_10_1 != other.a_10_1) return false;
            if (c_1_0 != other.c_1_0) return false;
            if (c_1_1 != other.c_1_1) return false;
            if (c_2_0 != other.c_2_0) return false;
            if (c_2_1 != other.c_2_1) return false;
            if (c_3_0 != other.c_3_0) return false;
            if (c_3_1 != other.c_3_1) return false;
            if (c_4_0 != other.c_4_0) return false;
            if (c_4_1 != other.c_4_1) return false;
            if (c_5_0 != other.c_5_0) return false;
            if (c_5_1 != other.c_5_1) return false;
            if (c_6_0 != other.c_6_0) return false;
            if (c_6_1 != other.c_6_1) return false;
            if (c_7_0 != other.c_7_0) return false;
            if (c_7_1 != other.c_7_1) return false;
            if (c_8_0 != other.c_8_0) return false;
            if (c_8_1 != other.c_8_1) return false;
            if (c_9_0 != other.c_9_0) return false;
            if (c_9_1 != other.c_9_1) return false;
            if (c_10_0 != other.c_10_0) return false;
            if (c_10_1 != other.c_10_1) return false;
            return true;
        }
    };
    test_iostruct hif_a2t_data;
    bool spec_sbm0__00_;
    bool spec_sbm0__01_;
    bool spec_sbm0__02_;
    bool spec_sbm0__03_;
    bool spec_sbm0__04_;
    bool spec_sbm0__05_;
    bool spec_sbm0__06_;
    bool spec_sbm0__07_;
    bool spec_sbm0__08_;
    bool spec_sbm0__09_;
    bool spec_sbm0__10_;
    bool spec_sbm0__11_;
    bool spec_sbm0__12_;
    bool spec_sbm0__13_;
    bool spec_sbm0__14_;
    bool spec_sbm0__15_;
    bool spec_sbm0__16_;
    bool spec_sbm0__17_;
    bool spec_sbm0__18_;
    bool spec_sbm0__19_;
    bool spec_sbm0__20_;
    bool spec_sbm0__21_;
    bool spec_sbm0__22_;
    bool spec_sbm0__23_;
    bool spec_sbm0__24_;
    bool spec_sbm0__25_;
    bool spec_sbm0__26_;
    bool spec_sbm0__27_;
    bool spec_sbm0__28_;
    bool spec_sbm0__29_;
    bool spec_sbm0__30_;
    bool spec_sbm0__31_;
    bool spec_sbm0__32_;
    bool spec_sbm0__33_;
    bool spec_sbm0__34_;
    bool spec_sbm0__35_;
    bool spec_sbm0__36_;
    bool spec_sbm0__37_;
    bool spec_sbm1__00_;
    bool spec_sbm1__01_;
    bool spec_sbm1__02_;
    bool spec_sbm1__03_;
    bool spec_sbm1__04_;
    bool spec_sbm1__05_;
    bool spec_sbm1__06_;
    bool spec_sbm1__07_;
    bool spec_sbm1__08_;
    bool spec_sbm1__09_;
    bool spec_sbm1__10_;
    bool spec_sbm1__11_;
    bool spec_sbm1__12_;
    bool spec_sbm1__13_;
    bool spec_sbm1__14_;
    bool spec_sbm1__15_;
    bool spec_sbm1__16_;
    bool spec_sbm1__17_;
    bool spec_sbm1__18_;
    bool spec_sbm1__19_;
    bool spec_sbm1__20_;
    bool spec_sbm1__21_;
    bool spec_sbm1__22_;
    bool spec_sbm1__23_;
    bool spec_sbm1__24_;
    bool spec_sbm1__25_;
    bool spec_sbm1__26_;
    bool spec_sbm1__27_;
    bool spec_sbm1__28_;
    bool spec_sbm1__29_;
    bool spec_sbm1__30_;
    bool spec_sbm1__31_;
    bool spec_sbm1__32_;
    bool spec_sbm1__33_;
    bool spec_sbm1__34_;
    bool spec_sbm1__35_;
    bool spec_sbm1__36_;
    bool spec_sbm1__37_;
    bool spec_sbm3__00_;
    bool spec_sbm3__01_;
    bool spec_sbm3__02_;
    bool spec_sbm3__03_;
    bool spec_sbm3__04_;
    bool spec_sbm3__05_;
    bool spec_sbm3__06_;
    bool spec_sbm3__07_;
    bool spec_sbm3__08_;
    bool spec_sbm3__09_;
    bool spec_sbm3__10_;
    bool spec_sbm3__11_;
    bool spec_sbm3__12_;
    bool spec_sbm3__13_;
    bool spec_sbm3__14_;
    bool spec_sbm3__15_;
    bool spec_sbm3__16_;
    bool spec_sbm3__17_;
    bool spec_sbm3__18_;
    bool spec_sbm3__19_;
    bool spec_sbm3__20_;
    bool spec_sbm3__21_;
    bool spec_sbm3__22_;
    bool spec_sbm3__23_;
    bool spec_sbm3__24_;
    bool spec_sbm3__25_;
    bool spec_sbm3__26_;
    bool spec_sbm3__27_;
    bool spec_sbm3__28_;
    bool spec_sbm3__29_;
    bool spec_sbm3__30_;
    bool spec_sbm3__31_;
    bool spec_sbm3__32_;
    bool spec_sbm3__33_;
    bool spec_sbm3__34_;
    bool spec_sbm3__35_;
    bool spec_sbm3__36_;
    bool spec_sbm3__37_;
    bool spec_sbm2__00_;
    bool spec_sbm2__01_;
    bool spec_sbm2__02_;
    bool spec_sbm2__03_;
    bool spec_sbm2__04_;
    bool spec_sbm2__05_;
    bool spec_sbm2__06_;
    bool spec_sbm2__07_;
    bool spec_sbm2__08_;
    bool spec_sbm2__09_;
    bool spec_sbm2__10_;
    bool spec_sbm2__11_;
    bool spec_sbm2__12_;
    bool spec_sbm2__13_;
    bool spec_sbm2__14_;
    bool spec_sbm2__15_;
    bool spec_sbm2__16_;
    bool spec_sbm2__17_;
    bool spec_sbm2__18_;
    bool spec_sbm2__19_;
    bool spec_sbm2__20_;
    bool spec_sbm2__21_;
    bool spec_sbm2__22_;
    bool spec_sbm2__23_;
    bool spec_sbm2__24_;
    bool spec_sbm2__25_;
    bool spec_sbm2__26_;
    bool spec_sbm2__27_;
    bool spec_sbm2__28_;
    bool spec_sbm2__29_;
    bool spec_sbm2__30_;
    bool spec_sbm2__31_;
    bool spec_sbm2__32_;
    bool spec_sbm2__33_;
    bool spec_sbm2__34_;
    bool spec_sbm2__35_;
    bool spec_sbm2__36_;
    bool spec_sbm2__37_;
    bool spec_sbm4__00_;
    bool spec_sbm4__01_;
    bool spec_sbm4__02_;
    bool spec_sbm4__03_;
    bool spec_sbm4__04_;
    bool spec_sbm4__05_;
    bool spec_sbm4__06_;
    bool spec_sbm4__07_;
    bool spec_sbm4__08_;
    bool spec_sbm4__09_;
    bool spec_sbm4__10_;
    bool spec_sbm4__11_;
    bool spec_sbm4__12_;
    bool spec_sbm4__13_;
    bool spec_sbm4__14_;
    bool spec_sbm4__15_;
    bool spec_sbm4__16_;
    bool spec_sbm4__17_;
    bool spec_sbm4__18_;
    bool spec_sbm4__19_;
    bool spec_sbm4__20_;
    bool spec_sbm4__21_;
    bool spec_sbm4__22_;
    bool spec_sbm4__23_;
    bool spec_sbm4__24_;
    bool spec_sbm4__25_;
    bool spec_sbm4__26_;
    bool spec_sbm4__27_;
    bool spec_sbm4__28_;
    bool spec_sbm4__29_;
    bool spec_sbm4__30_;
    bool spec_sbm4__31_;
    bool spec_sbm4__32_;
    bool spec_sbm4__33_;
    bool spec_sbm4__34_;
    bool spec_sbm4__35_;
    bool spec_sbm4__36_;
    bool spec_sbm4__37_;
    bool spec_sbm6__00_;
    bool spec_sbm6__01_;
    bool spec_sbm6__02_;
    bool spec_sbm6__03_;
    bool spec_sbm6__04_;
    bool spec_sbm6__05_;
    bool spec_sbm6__06_;
    bool spec_sbm6__07_;
    bool spec_sbm6__08_;
    bool spec_sbm6__09_;
    bool spec_sbm6__10_;
    bool spec_sbm6__11_;
    bool spec_sbm6__12_;
    bool spec_sbm6__13_;
    bool spec_sbm6__14_;
    bool spec_sbm6__15_;
    bool spec_sbm6__16_;
    bool spec_sbm6__17_;
    bool spec_sbm6__18_;
    bool spec_sbm6__19_;
    bool spec_sbm6__20_;
    bool spec_sbm6__21_;
    bool spec_sbm6__22_;
    bool spec_sbm6__23_;
    bool spec_sbm6__24_;
    bool spec_sbm6__25_;
    bool spec_sbm6__26_;
    bool spec_sbm6__27_;
    bool spec_sbm6__28_;
    bool spec_sbm6__29_;
    bool spec_sbm6__30_;
    bool spec_sbm6__31_;
    bool spec_sbm6__32_;
    bool spec_sbm6__33_;
    bool spec_sbm6__34_;
    bool spec_sbm6__35_;
    bool spec_sbm6__36_;
    bool spec_sbm6__37_;
    bool spec_sbm5__00_;
    bool spec_sbm5__01_;
    bool spec_sbm5__02_;
    bool spec_sbm5__03_;
    bool spec_sbm5__04_;
    bool spec_sbm5__05_;
    bool spec_sbm5__06_;
    bool spec_sbm5__07_;
    bool spec_sbm5__08_;
    bool spec_sbm5__09_;
    bool spec_sbm5__10_;
    bool spec_sbm5__11_;
    bool spec_sbm5__12_;
    bool spec_sbm5__13_;
    bool spec_sbm5__14_;
    bool spec_sbm5__15_;
    bool spec_sbm5__16_;
    bool spec_sbm5__17_;
    bool spec_sbm5__18_;
    bool spec_sbm5__19_;
    bool spec_sbm5__20_;
    bool spec_sbm5__21_;
    bool spec_sbm5__22_;
    bool spec_sbm5__23_;
    bool spec_sbm5__24_;
    bool spec_sbm5__25_;
    bool spec_sbm5__26_;
    bool spec_sbm5__27_;
    bool spec_sbm5__28_;
    bool spec_sbm5__29_;
    bool spec_sbm5__30_;
    bool spec_sbm5__31_;
    bool spec_sbm5__32_;
    bool spec_sbm5__33_;
    bool spec_sbm5__34_;
    bool spec_sbm5__35_;
    bool spec_sbm5__36_;
    bool spec_sbm5__37_;
    bool spec_sbm7__00_;
    bool spec_sbm7__01_;
    bool spec_sbm7__02_;
    bool spec_sbm7__03_;
    bool spec_sbm7__04_;
    bool spec_sbm7__05_;
    bool spec_sbm7__06_;
    bool spec_sbm7__07_;
    bool spec_sbm7__08_;
    bool spec_sbm7__09_;
    bool spec_sbm7__10_;
    bool spec_sbm7__11_;
    bool spec_sbm7__12_;
    bool spec_sbm7__13_;
    bool spec_sbm7__14_;
    bool spec_sbm7__15_;
    bool spec_sbm7__16_;
    bool spec_sbm7__17_;
    bool spec_sbm7__18_;
    bool spec_sbm7__19_;
    bool spec_sbm7__20_;
    bool spec_sbm7__21_;
    bool spec_sbm7__22_;
    bool spec_sbm7__23_;
    bool spec_sbm7__24_;
    bool spec_sbm7__25_;
    bool spec_sbm7__26_;
    bool spec_sbm7__27_;
    bool spec_sbm7__28_;
    bool spec_sbm7__29_;
    bool spec_sbm7__30_;
    bool spec_sbm7__31_;
    bool spec_sbm7__32_;
    bool spec_sbm7__33_;
    bool spec_sbm7__34_;
    bool spec_sbm7__35_;
    bool spec_sbm7__36_;
    bool spec_sbm7__37_;
    bool spec_sbm8__00_;
    bool spec_sbm8__01_;
    bool spec_sbm8__02_;
    bool spec_sbm8__03_;
    bool spec_sbm8__04_;
    bool spec_sbm8__05_;
    bool spec_sbm8__06_;
    bool spec_sbm8__07_;
    bool spec_sbm8__08_;
    bool spec_sbm8__09_;
    bool spec_sbm8__10_;
    bool spec_sbm8__11_;
    bool spec_sbm8__12_;
    bool spec_sbm8__13_;
    bool spec_sbm8__14_;
    bool spec_sbm8__15_;
    bool spec_sbm8__16_;
    bool spec_sbm8__17_;
    bool spec_sbm8__18_;
    bool spec_sbm8__19_;
    bool spec_sbm8__20_;
    bool spec_sbm8__21_;
    bool spec_sbm8__22_;
    bool spec_sbm8__23_;
    bool spec_sbm8__24_;
    bool spec_sbm8__25_;
    bool spec_sbm8__26_;
    bool spec_sbm8__27_;
    bool spec_sbm8__28_;
    bool spec_sbm8__29_;
    bool spec_sbm8__30_;
    bool spec_sbm8__31_;
    bool spec_sbm8__32_;
    bool spec_sbm8__33_;
    bool spec_sbm8__34_;
    bool spec_sbm8__35_;
    bool spec_sbm8__36_;
    bool spec_sbm8__37_;
    bool spec_sbm9__00_;
    bool spec_sbm9__01_;
    bool spec_sbm9__02_;
    bool spec_sbm9__03_;
    bool spec_sbm9__04_;
    bool spec_sbm9__05_;
    bool spec_sbm9__06_;
    bool spec_sbm9__07_;
    bool spec_sbm9__08_;
    bool spec_sbm9__09_;
    bool spec_sbm9__10_;
    bool spec_sbm9__11_;
    bool spec_sbm9__12_;
    bool spec_sbm9__13_;
    bool spec_sbm9__14_;
    bool spec_sbm9__15_;
    bool spec_sbm9__16_;
    bool spec_sbm9__17_;
    bool spec_sbm9__18_;
    bool spec_sbm9__19_;
    bool spec_sbm9__20_;
    bool spec_sbm9__21_;
    bool spec_sbm9__22_;
    bool spec_sbm9__23_;
    bool spec_sbm9__24_;
    bool spec_sbm9__25_;
    bool spec_sbm9__26_;
    bool spec_sbm9__27_;
    bool spec_sbm9__28_;
    bool spec_sbm9__29_;
    bool spec_sbm9__30_;
    bool spec_sbm9__31_;
    bool spec_sbm9__32_;
    bool spec_sbm9__33_;
    bool spec_sbm9__34_;
    bool spec_sbm9__35_;
    bool spec_sbm9__36_;
    bool spec_sbm9__37_;

    void hif_cone_spec_sbm0__24_();


    void hif_cone_spec_sbm0__29_();


    void hif_cone_spec_sbm1__24_();


    void hif_cone_spec_sbm1__29_();


    void hif_cone_spec_sbm2__24_();


    void hif_cone_spec_sbm2__29_();


    void hif_cone_spec_sbm3__24_();


    void hif_cone_spec_sbm3__29_();


    void hif_cone_spec_sbm4__24_();


    void hif_cone_spec_sbm4__29_();


    void hif_cone_spec_sbm5__24_();


    void hif_cone_spec_sbm5__29_();


    void hif_cone_spec_sbm6__24_();


    void hif_cone_spec_sbm6__29_();


    void hif_cone_spec_sbm7__24_();


    void hif_cone_spec_sbm7__29_();


    void hif_cone_spec_sbm8__24_();


    void hif_cone_spec_sbm8__29_();


    void hif_cone_spec_sbm9__24_();


    void hif_cone_spec_sbm9__29_();

    test();


    ~test();


    bool spec_sbm0__37__new;
    bool spec_sbm1__37__new;
    bool spec_sbm3__37__new;
    bool spec_sbm2__37__new;
    bool spec_sbm4__37__new;
    bool spec_sbm6__37__new;
    bool spec_sbm5__37__new;
    bool spec_sbm7__37__new;
    bool spec_sbm8__37__new;
    bool spec_sbm9__37__new;
    bool process_in_queue;
    bool flag_c_1_0;
    bool flag_c_2_0;
    bool flag_c_3_0;
    bool flag_c_4_0;
    bool flag_c_5_0;
    bool flag_c_6_0;
    bool flag_c_7_0;
    bool flag_c_8_0;
    bool flag_c_9_0;
    bool flag_c_10_0;
    bool flag_spec_sbm0_process_spec_sbm0_process_0_spec_sbm1_process_1_spec_sbm1_process_2_spec_sbm3_process_5_spec_sbm3_process_6_spec_sbm2_process_3_spec_sbm2_process_4_spec_sbm4_process_7_spec_sbm4_process_8_spec_sbm6_process_11_spec_sbm6_process_12_spec_sbm5_process_9_spec_sbm5_process_10_spec_sbm7_process_13_spec_sbm7_process_14_spec_sbm8_process_15_spec_sbm8_process_16_spec_sbm9_process_17_spec_sbm9_process_18_executed;
    bool flag_pos_clock;

    void globact_process();


    void globact_process_0();


    void globact_process_1();


    void globact_process_2();


    void globact_process_3();


    void globact_process_4();


    void globact_process_5();


    void globact_process_6();


    void globact_process_7();


    void globact_process_8();


    void spec_sbm0_process_spec_sbm0_process_0_spec_sbm1_process_1_spec_sbm1_process_2_spec_sbm3_process_5_spec_sbm3_process_6_spec_sbm2_process_3_spec_sbm2_process_4_spec_sbm4_process_7_spec_sbm4_process_8_spec_sbm6_process_11_spec_sbm6_process_12_spec_sbm5_process_9_spec_sbm5_process_10_spec_sbm7_process_13_spec_sbm7_process_14_spec_sbm8_process_15_spec_sbm8_process_16_spec_sbm9_process_17_spec_sbm9_process_18
        ();


    void update_input_queue( bool synch_phase = true );


    void update_event_queue();


    void flag_elaboration();


    void synch_elaboration();


    void simulate( test_iostruct * io_exchange, int32_t & cycles_number );


    void start_of_simulation();


    void initialize();


    void finalize();


private:

    test( const test & );
    const test& operator= ( const test & );


};


#endif

