/* Generated by Yosys 0.47+149 (git sha1 384c19119, clang++ 18.1.8 -fPIC -O3) */

module spec2(clock, a_2, b_2, c_2);
input clock;
wire clock;
  input a_2;
  wire a_2;
  input b_2;
  wire b_2;
  output c_2;
  wire c_2;
  assign c_2 = ~1'h0;
endmodule
