/* Generated by Yosys 0.47+149 (git sha1 384c19119, clang++ 18.1.8 -fPIC -O3) */

module spec5(clock, a_5, b_5, c_5);
input clock;
wire clock;
  input a_5;
  wire a_5;
  input b_5;
  wire b_5;
  output c_5;
  wire c_5;
  assign c_5 = ~1'h0;
endmodule
