/* Generated by Yosys 0.47+149 (git sha1 384c19119, clang++ 18.1.8 -fPIC -O3) */

module spec0(clock, a_0, b_0, c_0);
input clock;
wire clock;
  input a_0;
  wire a_0;
  input b_0;
  wire b_0;
  output c_0;
  wire c_0;
  assign c_0 = ~1'h0;
endmodule
