/* Generated by Yosys 0.47+149 (git sha1 384c19119, clang++ 18.1.8 -fPIC -O3) */

module spec4(clock, a_4, b_4, c_4);
input clock;
wire clock;
  input a_4;
  wire a_4;
  input b_4;
  wire b_4;
  output c_4;
  wire c_4;
  assign c_4 = ~1'h0;
endmodule
