// /////////////////////////////////////////////////////////////////////////
// C++ code automatically generated by hif2sc
// Part of HIFSuite - Version 
// Site: www.hifsuite.com - Contact: hifsuite@edalab.it
//
// HIFSuite copyright: EDALab s.r.l. - Networked Embedded Systems
// Site: www.edalab.it - Contact: info@edalab.it
// /////////////////////////////////////////////////////////////////////////


#include "../inc/test.hpp"


void test::hif_cone_spec_sbm0__24_()
{
    spec_sbm0__13_ = muffin::inject( hif_fault_node.instance, 0ULL, 1ULL, !hif_a2t_data.a_1_0
         );
    spec_sbm0__25_ = muffin::inject( hif_fault_node.instance, 1ULL, 1ULL, !hif_a2t_data.a_1_1
         );
    spec_sbm0__31_ = muffin::inject( hif_fault_node.instance, 2ULL, 1ULL, !c_1_0_old
         );
    spec_sbm0__30_ = muffin::inject( hif_fault_node.instance, 3ULL, 1ULL, !spec_sbm0__37_
         );
    spec_sbm0__08_ = muffin::inject( hif_fault_node.instance, 4ULL, 1ULL, c_1_0_old
             && spec_sbm0__30_ );
    spec_sbm0__05_ = muffin::inject( hif_fault_node.instance, 5ULL, 1ULL, hif_a2t_data.a_1_1
             && spec_sbm0__13_ );
    spec_sbm0__16_ = muffin::inject( hif_fault_node.instance, 6ULL, 1ULL, c_1_0_old
             && spec_sbm0__37_ );
    spec_sbm0__36_ = muffin::inject( hif_fault_node.instance, 7ULL, 1ULL, spec_sbm0__31_
             && spec_sbm0__37_ );
    spec_sbm0__35_ = muffin::inject( hif_fault_node.instance, 8ULL, 1ULL, hif_a2t_data.a_1_0
             && spec_sbm0__25_ );
    spec_sbm0__00_ = muffin::inject( hif_fault_node.instance, 9ULL, 1ULL, spec_sbm0__35_
             && spec_sbm0__36_ );
    spec_sbm0__06_ = muffin::inject( hif_fault_node.instance, 10ULL, 1ULL, spec_sbm0__05_
             && spec_sbm0__36_ );
    spec_sbm0__14_ = muffin::inject( hif_fault_node.instance, 11ULL, 1ULL, spec_sbm0__08_
             && spec_sbm0__35_ );
    spec_sbm0__17_ = muffin::inject( hif_fault_node.instance, 12ULL, 1ULL, hif_a2t_data.a_1_0
             && spec_sbm0__16_ );
    spec_sbm0__32_ = muffin::inject( hif_fault_node.instance, 13ULL, 1ULL, spec_sbm0__30_
             && spec_sbm0__31_ );
    spec_sbm0__01_ = muffin::inject( hif_fault_node.instance, 14ULL, 1ULL, !spec_sbm0__00_
         );
    spec_sbm0__07_ = muffin::inject( hif_fault_node.instance, 15ULL, 1ULL, !spec_sbm0__06_
         );
    spec_sbm0__15_ = muffin::inject( hif_fault_node.instance, 16ULL, 1ULL, !spec_sbm0__14_
         );
    spec_sbm0__11_ = muffin::inject( hif_fault_node.instance, 17ULL, 1ULL, spec_sbm0__05_
             && spec_sbm0__08_ );
    spec_sbm0__18_ = muffin::inject( hif_fault_node.instance, 18ULL, 1ULL, !spec_sbm0__17_
         );
    spec_sbm0__33_ = muffin::inject( hif_fault_node.instance, 19ULL, 1ULL, hif_a2t_data.a_1_0
             && spec_sbm0__32_ );
    spec_sbm0__12_ = muffin::inject( hif_fault_node.instance, 20ULL, 1ULL, !spec_sbm0__11_
         );
    spec_sbm0__21_ = muffin::inject( hif_fault_node.instance, 21ULL, 1ULL, spec_sbm0__15_
             && spec_sbm0__18_ );
    spec_sbm0__19_ = muffin::inject( hif_fault_node.instance, 22ULL, 1ULL, spec_sbm0__01_
             && spec_sbm0__07_ );
    spec_sbm0__34_ = muffin::inject( hif_fault_node.instance, 23ULL, 1ULL, !spec_sbm0__33_
         );
    spec_sbm0__22_ = muffin::inject( hif_fault_node.instance, 24ULL, 1ULL, spec_sbm0__12_
             && spec_sbm0__21_ );
    spec_sbm0__20_ = muffin::inject( hif_fault_node.instance, 25ULL, 1ULL, spec_sbm0__19_
             && spec_sbm0__34_ );
    spec_sbm0__23_ = muffin::inject( hif_fault_node.instance, 26ULL, 1ULL, spec_sbm0__20_
             && spec_sbm0__22_ );
    spec_sbm0__24_ = muffin::inject( hif_fault_node.instance, 27ULL, 1ULL, !spec_sbm0__23_
         );
}


void test::hif_cone_spec_sbm0__29_()
{
    spec_sbm0__13_ = muffin::inject( hif_fault_node.instance, 28ULL, 1ULL, !hif_a2t_data.a_1_0
         );
    spec_sbm0__31_ = muffin::inject( hif_fault_node.instance, 29ULL, 1ULL, !c_1_0_old
         );
    spec_sbm0__30_ = muffin::inject( hif_fault_node.instance, 30ULL, 1ULL, !spec_sbm0__37_
         );
    spec_sbm0__08_ = muffin::inject( hif_fault_node.instance, 31ULL, 1ULL, c_1_0_old
             && spec_sbm0__30_ );
    spec_sbm0__05_ = muffin::inject( hif_fault_node.instance, 32ULL, 1ULL, hif_a2t_data.a_1_1
             && spec_sbm0__13_ );
    spec_sbm0__36_ = muffin::inject( hif_fault_node.instance, 33ULL, 1ULL, spec_sbm0__31_
             && spec_sbm0__37_ );
    spec_sbm0__06_ = muffin::inject( hif_fault_node.instance, 34ULL, 1ULL, spec_sbm0__05_
             && spec_sbm0__36_ );
    spec_sbm0__02_ = muffin::inject( hif_fault_node.instance, 35ULL, 1ULL, hif_a2t_data.a_1_0
             && hif_a2t_data.a_1_1 );
    spec_sbm0__07_ = muffin::inject( hif_fault_node.instance, 36ULL, 1ULL, !spec_sbm0__06_
         );
    spec_sbm0__03_ = muffin::inject( hif_fault_node.instance, 37ULL, 1ULL, spec_sbm0__02_
             && spec_sbm0__36_ );
    spec_sbm0__09_ = muffin::inject( hif_fault_node.instance, 38ULL, 1ULL, spec_sbm0__02_
             && spec_sbm0__08_ );
    spec_sbm0__11_ = muffin::inject( hif_fault_node.instance, 39ULL, 1ULL, spec_sbm0__05_
             && spec_sbm0__08_ );
    spec_sbm0__04_ = muffin::inject( hif_fault_node.instance, 40ULL, 1ULL, !spec_sbm0__03_
         );
    spec_sbm0__12_ = muffin::inject( hif_fault_node.instance, 41ULL, 1ULL, !spec_sbm0__11_
         );
    spec_sbm0__10_ = muffin::inject( hif_fault_node.instance, 42ULL, 1ULL, !spec_sbm0__09_
         );
    spec_sbm0__27_ = muffin::inject( hif_fault_node.instance, 43ULL, 1ULL, spec_sbm0__10_
             && spec_sbm0__12_ );
    spec_sbm0__26_ = muffin::inject( hif_fault_node.instance, 44ULL, 1ULL, spec_sbm0__04_
             && spec_sbm0__07_ );
    spec_sbm0__28_ = muffin::inject( hif_fault_node.instance, 45ULL, 1ULL, spec_sbm0__26_
             && spec_sbm0__27_ );
    spec_sbm0__29_ = muffin::inject( hif_fault_node.instance, 46ULL, 1ULL, !spec_sbm0__28_
         );
}


void test::hif_cone_spec_sbm1__24_()
{
    spec_sbm1__13_ = muffin::inject( hif_fault_node.instance, 47ULL, 1ULL, !hif_a2t_data.a_2_0
         );
    spec_sbm1__25_ = muffin::inject( hif_fault_node.instance, 48ULL, 1ULL, !hif_a2t_data.a_2_1
         );
    spec_sbm1__31_ = muffin::inject( hif_fault_node.instance, 49ULL, 1ULL, !c_2_0_old
         );
    spec_sbm1__30_ = muffin::inject( hif_fault_node.instance, 50ULL, 1ULL, !spec_sbm1__37_
         );
    spec_sbm1__08_ = muffin::inject( hif_fault_node.instance, 51ULL, 1ULL, c_2_0_old
             && spec_sbm1__30_ );
    spec_sbm1__05_ = muffin::inject( hif_fault_node.instance, 52ULL, 1ULL, hif_a2t_data.a_2_1
             && spec_sbm1__13_ );
    spec_sbm1__16_ = muffin::inject( hif_fault_node.instance, 53ULL, 1ULL, c_2_0_old
             && spec_sbm1__37_ );
    spec_sbm1__35_ = muffin::inject( hif_fault_node.instance, 54ULL, 1ULL, hif_a2t_data.a_2_0
             && spec_sbm1__25_ );
    spec_sbm1__36_ = muffin::inject( hif_fault_node.instance, 55ULL, 1ULL, spec_sbm1__31_
             && spec_sbm1__37_ );
    spec_sbm1__00_ = muffin::inject( hif_fault_node.instance, 56ULL, 1ULL, spec_sbm1__35_
             && spec_sbm1__36_ );
    spec_sbm1__06_ = muffin::inject( hif_fault_node.instance, 57ULL, 1ULL, spec_sbm1__05_
             && spec_sbm1__36_ );
    spec_sbm1__17_ = muffin::inject( hif_fault_node.instance, 58ULL, 1ULL, hif_a2t_data.a_2_0
             && spec_sbm1__16_ );
    spec_sbm1__14_ = muffin::inject( hif_fault_node.instance, 59ULL, 1ULL, spec_sbm1__08_
             && spec_sbm1__35_ );
    spec_sbm1__32_ = muffin::inject( hif_fault_node.instance, 60ULL, 1ULL, spec_sbm1__30_
             && spec_sbm1__31_ );
    spec_sbm1__01_ = muffin::inject( hif_fault_node.instance, 61ULL, 1ULL, !spec_sbm1__00_
         );
    spec_sbm1__11_ = muffin::inject( hif_fault_node.instance, 62ULL, 1ULL, spec_sbm1__05_
             && spec_sbm1__08_ );
    spec_sbm1__07_ = muffin::inject( hif_fault_node.instance, 63ULL, 1ULL, !spec_sbm1__06_
         );
    spec_sbm1__18_ = muffin::inject( hif_fault_node.instance, 64ULL, 1ULL, !spec_sbm1__17_
         );
    spec_sbm1__15_ = muffin::inject( hif_fault_node.instance, 65ULL, 1ULL, !spec_sbm1__14_
         );
    spec_sbm1__33_ = muffin::inject( hif_fault_node.instance, 66ULL, 1ULL, hif_a2t_data.a_2_0
             && spec_sbm1__32_ );
    spec_sbm1__12_ = muffin::inject( hif_fault_node.instance, 67ULL, 1ULL, !spec_sbm1__11_
         );
    spec_sbm1__19_ = muffin::inject( hif_fault_node.instance, 68ULL, 1ULL, spec_sbm1__01_
             && spec_sbm1__07_ );
    spec_sbm1__21_ = muffin::inject( hif_fault_node.instance, 69ULL, 1ULL, spec_sbm1__15_
             && spec_sbm1__18_ );
    spec_sbm1__34_ = muffin::inject( hif_fault_node.instance, 70ULL, 1ULL, !spec_sbm1__33_
         );
    spec_sbm1__20_ = muffin::inject( hif_fault_node.instance, 71ULL, 1ULL, spec_sbm1__19_
             && spec_sbm1__34_ );
    spec_sbm1__22_ = muffin::inject( hif_fault_node.instance, 72ULL, 1ULL, spec_sbm1__12_
             && spec_sbm1__21_ );
    spec_sbm1__23_ = muffin::inject( hif_fault_node.instance, 73ULL, 1ULL, spec_sbm1__20_
             && spec_sbm1__22_ );
    spec_sbm1__24_ = muffin::inject( hif_fault_node.instance, 74ULL, 1ULL, !spec_sbm1__23_
         );
}


void test::hif_cone_spec_sbm1__29_()
{
    spec_sbm1__13_ = muffin::inject( hif_fault_node.instance, 75ULL, 1ULL, !hif_a2t_data.a_2_0
         );
    spec_sbm1__31_ = muffin::inject( hif_fault_node.instance, 76ULL, 1ULL, !c_2_0_old
         );
    spec_sbm1__30_ = muffin::inject( hif_fault_node.instance, 77ULL, 1ULL, !spec_sbm1__37_
         );
    spec_sbm1__08_ = muffin::inject( hif_fault_node.instance, 78ULL, 1ULL, c_2_0_old
             && spec_sbm1__30_ );
    spec_sbm1__05_ = muffin::inject( hif_fault_node.instance, 79ULL, 1ULL, hif_a2t_data.a_2_1
             && spec_sbm1__13_ );
    spec_sbm1__36_ = muffin::inject( hif_fault_node.instance, 80ULL, 1ULL, spec_sbm1__31_
             && spec_sbm1__37_ );
    spec_sbm1__02_ = muffin::inject( hif_fault_node.instance, 81ULL, 1ULL, hif_a2t_data.a_2_0
             && hif_a2t_data.a_2_1 );
    spec_sbm1__06_ = muffin::inject( hif_fault_node.instance, 82ULL, 1ULL, spec_sbm1__05_
             && spec_sbm1__36_ );
    spec_sbm1__03_ = muffin::inject( hif_fault_node.instance, 83ULL, 1ULL, spec_sbm1__02_
             && spec_sbm1__36_ );
    spec_sbm1__11_ = muffin::inject( hif_fault_node.instance, 84ULL, 1ULL, spec_sbm1__05_
             && spec_sbm1__08_ );
    spec_sbm1__09_ = muffin::inject( hif_fault_node.instance, 85ULL, 1ULL, spec_sbm1__02_
             && spec_sbm1__08_ );
    spec_sbm1__07_ = muffin::inject( hif_fault_node.instance, 86ULL, 1ULL, !spec_sbm1__06_
         );
    spec_sbm1__04_ = muffin::inject( hif_fault_node.instance, 87ULL, 1ULL, !spec_sbm1__03_
         );
    spec_sbm1__10_ = muffin::inject( hif_fault_node.instance, 88ULL, 1ULL, !spec_sbm1__09_
         );
    spec_sbm1__12_ = muffin::inject( hif_fault_node.instance, 89ULL, 1ULL, !spec_sbm1__11_
         );
    spec_sbm1__27_ = muffin::inject( hif_fault_node.instance, 90ULL, 1ULL, spec_sbm1__10_
             && spec_sbm1__12_ );
    spec_sbm1__26_ = muffin::inject( hif_fault_node.instance, 91ULL, 1ULL, spec_sbm1__04_
             && spec_sbm1__07_ );
    spec_sbm1__28_ = muffin::inject( hif_fault_node.instance, 92ULL, 1ULL, spec_sbm1__26_
             && spec_sbm1__27_ );
    spec_sbm1__29_ = muffin::inject( hif_fault_node.instance, 93ULL, 1ULL, !spec_sbm1__28_
         );
}


void test::hif_cone_spec_sbm2__24_()
{
    spec_sbm2__13_ = muffin::inject( hif_fault_node.instance, 94ULL, 1ULL, !hif_a2t_data.a_3_0
         );
    spec_sbm2__25_ = muffin::inject( hif_fault_node.instance, 95ULL, 1ULL, !hif_a2t_data.a_3_1
         );
    spec_sbm2__30_ = muffin::inject( hif_fault_node.instance, 96ULL, 1ULL, !spec_sbm2__37_
         );
    spec_sbm2__31_ = muffin::inject( hif_fault_node.instance, 97ULL, 1ULL, !c_3_0_old
         );
    spec_sbm2__05_ = muffin::inject( hif_fault_node.instance, 98ULL, 1ULL, hif_a2t_data.a_3_1
             && spec_sbm2__13_ );
    spec_sbm2__08_ = muffin::inject( hif_fault_node.instance, 99ULL, 1ULL, c_3_0_old
             && spec_sbm2__30_ );
    spec_sbm2__16_ = muffin::inject( hif_fault_node.instance, 100ULL, 1ULL, c_3_0_old
             && spec_sbm2__37_ );
    spec_sbm2__35_ = muffin::inject( hif_fault_node.instance, 101ULL, 1ULL, hif_a2t_data.a_3_0
             && spec_sbm2__25_ );
    spec_sbm2__36_ = muffin::inject( hif_fault_node.instance, 102ULL, 1ULL, spec_sbm2__31_
             && spec_sbm2__37_ );
    spec_sbm2__00_ = muffin::inject( hif_fault_node.instance, 103ULL, 1ULL, spec_sbm2__35_
             && spec_sbm2__36_ );
    spec_sbm2__06_ = muffin::inject( hif_fault_node.instance, 104ULL, 1ULL, spec_sbm2__05_
             && spec_sbm2__36_ );
    spec_sbm2__14_ = muffin::inject( hif_fault_node.instance, 105ULL, 1ULL, spec_sbm2__08_
             && spec_sbm2__35_ );
    spec_sbm2__17_ = muffin::inject( hif_fault_node.instance, 106ULL, 1ULL, hif_a2t_data.a_3_0
             && spec_sbm2__16_ );
    spec_sbm2__32_ = muffin::inject( hif_fault_node.instance, 107ULL, 1ULL, spec_sbm2__30_
             && spec_sbm2__31_ );
    spec_sbm2__11_ = muffin::inject( hif_fault_node.instance, 108ULL, 1ULL, spec_sbm2__05_
             && spec_sbm2__08_ );
    spec_sbm2__07_ = muffin::inject( hif_fault_node.instance, 109ULL, 1ULL, !spec_sbm2__06_
         );
    spec_sbm2__15_ = muffin::inject( hif_fault_node.instance, 110ULL, 1ULL, !spec_sbm2__14_
         );
    spec_sbm2__18_ = muffin::inject( hif_fault_node.instance, 111ULL, 1ULL, !spec_sbm2__17_
         );
    spec_sbm2__33_ = muffin::inject( hif_fault_node.instance, 112ULL, 1ULL, hif_a2t_data.a_3_0
             && spec_sbm2__32_ );
    spec_sbm2__01_ = muffin::inject( hif_fault_node.instance, 113ULL, 1ULL, !spec_sbm2__00_
         );
    spec_sbm2__12_ = muffin::inject( hif_fault_node.instance, 114ULL, 1ULL, !spec_sbm2__11_
         );
    spec_sbm2__19_ = muffin::inject( hif_fault_node.instance, 115ULL, 1ULL, spec_sbm2__01_
             && spec_sbm2__07_ );
    spec_sbm2__21_ = muffin::inject( hif_fault_node.instance, 116ULL, 1ULL, spec_sbm2__15_
             && spec_sbm2__18_ );
    spec_sbm2__34_ = muffin::inject( hif_fault_node.instance, 117ULL, 1ULL, !spec_sbm2__33_
         );
    spec_sbm2__20_ = muffin::inject( hif_fault_node.instance, 118ULL, 1ULL, spec_sbm2__19_
             && spec_sbm2__34_ );
    spec_sbm2__22_ = muffin::inject( hif_fault_node.instance, 119ULL, 1ULL, spec_sbm2__12_
             && spec_sbm2__21_ );
    spec_sbm2__23_ = muffin::inject( hif_fault_node.instance, 120ULL, 1ULL, spec_sbm2__20_
             && spec_sbm2__22_ );
    spec_sbm2__24_ = muffin::inject( hif_fault_node.instance, 121ULL, 1ULL, !spec_sbm2__23_
         );
}


void test::hif_cone_spec_sbm2__29_()
{
    spec_sbm2__13_ = muffin::inject( hif_fault_node.instance, 122ULL, 1ULL, !hif_a2t_data.a_3_0
         );
    spec_sbm2__30_ = muffin::inject( hif_fault_node.instance, 123ULL, 1ULL, !spec_sbm2__37_
         );
    spec_sbm2__31_ = muffin::inject( hif_fault_node.instance, 124ULL, 1ULL, !c_3_0_old
         );
    spec_sbm2__05_ = muffin::inject( hif_fault_node.instance, 125ULL, 1ULL, hif_a2t_data.a_3_1
             && spec_sbm2__13_ );
    spec_sbm2__08_ = muffin::inject( hif_fault_node.instance, 126ULL, 1ULL, c_3_0_old
             && spec_sbm2__30_ );
    spec_sbm2__36_ = muffin::inject( hif_fault_node.instance, 127ULL, 1ULL, spec_sbm2__31_
             && spec_sbm2__37_ );
    spec_sbm2__06_ = muffin::inject( hif_fault_node.instance, 128ULL, 1ULL, spec_sbm2__05_
             && spec_sbm2__36_ );
    spec_sbm2__02_ = muffin::inject( hif_fault_node.instance, 129ULL, 1ULL, hif_a2t_data.a_3_0
             && hif_a2t_data.a_3_1 );
    spec_sbm2__11_ = muffin::inject( hif_fault_node.instance, 130ULL, 1ULL, spec_sbm2__05_
             && spec_sbm2__08_ );
    spec_sbm2__07_ = muffin::inject( hif_fault_node.instance, 131ULL, 1ULL, !spec_sbm2__06_
         );
    spec_sbm2__09_ = muffin::inject( hif_fault_node.instance, 132ULL, 1ULL, spec_sbm2__02_
             && spec_sbm2__08_ );
    spec_sbm2__03_ = muffin::inject( hif_fault_node.instance, 133ULL, 1ULL, spec_sbm2__02_
             && spec_sbm2__36_ );
    spec_sbm2__04_ = muffin::inject( hif_fault_node.instance, 134ULL, 1ULL, !spec_sbm2__03_
         );
    spec_sbm2__12_ = muffin::inject( hif_fault_node.instance, 135ULL, 1ULL, !spec_sbm2__11_
         );
    spec_sbm2__10_ = muffin::inject( hif_fault_node.instance, 136ULL, 1ULL, !spec_sbm2__09_
         );
    spec_sbm2__27_ = muffin::inject( hif_fault_node.instance, 137ULL, 1ULL, spec_sbm2__10_
             && spec_sbm2__12_ );
    spec_sbm2__26_ = muffin::inject( hif_fault_node.instance, 138ULL, 1ULL, spec_sbm2__04_
             && spec_sbm2__07_ );
    spec_sbm2__28_ = muffin::inject( hif_fault_node.instance, 139ULL, 1ULL, spec_sbm2__26_
             && spec_sbm2__27_ );
    spec_sbm2__29_ = muffin::inject( hif_fault_node.instance, 140ULL, 1ULL, !spec_sbm2__28_
         );
}


void test::hif_cone_spec_sbm3__24_()
{
    spec_sbm3__30_ = muffin::inject( hif_fault_node.instance, 141ULL, 1ULL, !spec_sbm3__37_
         );
    spec_sbm3__31_ = muffin::inject( hif_fault_node.instance, 142ULL, 1ULL, !c_4_0_old
         );
    spec_sbm3__25_ = muffin::inject( hif_fault_node.instance, 143ULL, 1ULL, !hif_a2t_data.a_4_1
         );
    spec_sbm3__13_ = muffin::inject( hif_fault_node.instance, 144ULL, 1ULL, !hif_a2t_data.a_4_0
         );
    spec_sbm3__36_ = muffin::inject( hif_fault_node.instance, 145ULL, 1ULL, spec_sbm3__31_
             && spec_sbm3__37_ );
    spec_sbm3__08_ = muffin::inject( hif_fault_node.instance, 146ULL, 1ULL, c_4_0_old
             && spec_sbm3__30_ );
    spec_sbm3__16_ = muffin::inject( hif_fault_node.instance, 147ULL, 1ULL, c_4_0_old
             && spec_sbm3__37_ );
    spec_sbm3__05_ = muffin::inject( hif_fault_node.instance, 148ULL, 1ULL, hif_a2t_data.a_4_1
             && spec_sbm3__13_ );
    spec_sbm3__35_ = muffin::inject( hif_fault_node.instance, 149ULL, 1ULL, hif_a2t_data.a_4_0
             && spec_sbm3__25_ );
    spec_sbm3__00_ = muffin::inject( hif_fault_node.instance, 150ULL, 1ULL, spec_sbm3__35_
             && spec_sbm3__36_ );
    spec_sbm3__06_ = muffin::inject( hif_fault_node.instance, 151ULL, 1ULL, spec_sbm3__05_
             && spec_sbm3__36_ );
    spec_sbm3__17_ = muffin::inject( hif_fault_node.instance, 152ULL, 1ULL, hif_a2t_data.a_4_0
             && spec_sbm3__16_ );
    spec_sbm3__14_ = muffin::inject( hif_fault_node.instance, 153ULL, 1ULL, spec_sbm3__08_
             && spec_sbm3__35_ );
    spec_sbm3__32_ = muffin::inject( hif_fault_node.instance, 154ULL, 1ULL, spec_sbm3__30_
             && spec_sbm3__31_ );
    spec_sbm3__01_ = muffin::inject( hif_fault_node.instance, 155ULL, 1ULL, !spec_sbm3__00_
         );
    spec_sbm3__07_ = muffin::inject( hif_fault_node.instance, 156ULL, 1ULL, !spec_sbm3__06_
         );
    spec_sbm3__11_ = muffin::inject( hif_fault_node.instance, 157ULL, 1ULL, spec_sbm3__05_
             && spec_sbm3__08_ );
    spec_sbm3__15_ = muffin::inject( hif_fault_node.instance, 158ULL, 1ULL, !spec_sbm3__14_
         );
    spec_sbm3__18_ = muffin::inject( hif_fault_node.instance, 159ULL, 1ULL, !spec_sbm3__17_
         );
    spec_sbm3__33_ = muffin::inject( hif_fault_node.instance, 160ULL, 1ULL, hif_a2t_data.a_4_0
             && spec_sbm3__32_ );
    spec_sbm3__19_ = muffin::inject( hif_fault_node.instance, 161ULL, 1ULL, spec_sbm3__01_
             && spec_sbm3__07_ );
    spec_sbm3__12_ = muffin::inject( hif_fault_node.instance, 162ULL, 1ULL, !spec_sbm3__11_
         );
    spec_sbm3__34_ = muffin::inject( hif_fault_node.instance, 163ULL, 1ULL, !spec_sbm3__33_
         );
    spec_sbm3__21_ = muffin::inject( hif_fault_node.instance, 164ULL, 1ULL, spec_sbm3__15_
             && spec_sbm3__18_ );
    spec_sbm3__20_ = muffin::inject( hif_fault_node.instance, 165ULL, 1ULL, spec_sbm3__19_
             && spec_sbm3__34_ );
    spec_sbm3__22_ = muffin::inject( hif_fault_node.instance, 166ULL, 1ULL, spec_sbm3__12_
             && spec_sbm3__21_ );
    spec_sbm3__23_ = muffin::inject( hif_fault_node.instance, 167ULL, 1ULL, spec_sbm3__20_
             && spec_sbm3__22_ );
    spec_sbm3__24_ = muffin::inject( hif_fault_node.instance, 168ULL, 1ULL, !spec_sbm3__23_
         );
}


void test::hif_cone_spec_sbm3__29_()
{
    spec_sbm3__30_ = muffin::inject( hif_fault_node.instance, 169ULL, 1ULL, !spec_sbm3__37_
         );
    spec_sbm3__31_ = muffin::inject( hif_fault_node.instance, 170ULL, 1ULL, !c_4_0_old
         );
    spec_sbm3__13_ = muffin::inject( hif_fault_node.instance, 171ULL, 1ULL, !hif_a2t_data.a_4_0
         );
    spec_sbm3__36_ = muffin::inject( hif_fault_node.instance, 172ULL, 1ULL, spec_sbm3__31_
             && spec_sbm3__37_ );
    spec_sbm3__08_ = muffin::inject( hif_fault_node.instance, 173ULL, 1ULL, c_4_0_old
             && spec_sbm3__30_ );
    spec_sbm3__05_ = muffin::inject( hif_fault_node.instance, 174ULL, 1ULL, hif_a2t_data.a_4_1
             && spec_sbm3__13_ );
    spec_sbm3__02_ = muffin::inject( hif_fault_node.instance, 175ULL, 1ULL, hif_a2t_data.a_4_0
             && hif_a2t_data.a_4_1 );
    spec_sbm3__06_ = muffin::inject( hif_fault_node.instance, 176ULL, 1ULL, spec_sbm3__05_
             && spec_sbm3__36_ );
    spec_sbm3__03_ = muffin::inject( hif_fault_node.instance, 177ULL, 1ULL, spec_sbm3__02_
             && spec_sbm3__36_ );
    spec_sbm3__07_ = muffin::inject( hif_fault_node.instance, 178ULL, 1ULL, !spec_sbm3__06_
         );
    spec_sbm3__09_ = muffin::inject( hif_fault_node.instance, 179ULL, 1ULL, spec_sbm3__02_
             && spec_sbm3__08_ );
    spec_sbm3__11_ = muffin::inject( hif_fault_node.instance, 180ULL, 1ULL, spec_sbm3__05_
             && spec_sbm3__08_ );
    spec_sbm3__10_ = muffin::inject( hif_fault_node.instance, 181ULL, 1ULL, !spec_sbm3__09_
         );
    spec_sbm3__04_ = muffin::inject( hif_fault_node.instance, 182ULL, 1ULL, !spec_sbm3__03_
         );
    spec_sbm3__12_ = muffin::inject( hif_fault_node.instance, 183ULL, 1ULL, !spec_sbm3__11_
         );
    spec_sbm3__26_ = muffin::inject( hif_fault_node.instance, 184ULL, 1ULL, spec_sbm3__04_
             && spec_sbm3__07_ );
    spec_sbm3__27_ = muffin::inject( hif_fault_node.instance, 185ULL, 1ULL, spec_sbm3__10_
             && spec_sbm3__12_ );
    spec_sbm3__28_ = muffin::inject( hif_fault_node.instance, 186ULL, 1ULL, spec_sbm3__26_
             && spec_sbm3__27_ );
    spec_sbm3__29_ = muffin::inject( hif_fault_node.instance, 187ULL, 1ULL, !spec_sbm3__28_
         );
}


void test::hif_cone_spec_sbm4__24_()
{
    spec_sbm4__25_ = muffin::inject( hif_fault_node.instance, 188ULL, 1ULL, !hif_a2t_data.a_5_1
         );
    spec_sbm4__13_ = muffin::inject( hif_fault_node.instance, 189ULL, 1ULL, !hif_a2t_data.a_5_0
         );
    spec_sbm4__30_ = muffin::inject( hif_fault_node.instance, 190ULL, 1ULL, !spec_sbm4__37_
         );
    spec_sbm4__31_ = muffin::inject( hif_fault_node.instance, 191ULL, 1ULL, !c_5_0_old
         );
    spec_sbm4__08_ = muffin::inject( hif_fault_node.instance, 192ULL, 1ULL, c_5_0_old
             && spec_sbm4__30_ );
    spec_sbm4__16_ = muffin::inject( hif_fault_node.instance, 193ULL, 1ULL, c_5_0_old
             && spec_sbm4__37_ );
    spec_sbm4__05_ = muffin::inject( hif_fault_node.instance, 194ULL, 1ULL, hif_a2t_data.a_5_1
             && spec_sbm4__13_ );
    spec_sbm4__35_ = muffin::inject( hif_fault_node.instance, 195ULL, 1ULL, hif_a2t_data.a_5_0
             && spec_sbm4__25_ );
    spec_sbm4__36_ = muffin::inject( hif_fault_node.instance, 196ULL, 1ULL, spec_sbm4__31_
             && spec_sbm4__37_ );
    spec_sbm4__17_ = muffin::inject( hif_fault_node.instance, 197ULL, 1ULL, hif_a2t_data.a_5_0
             && spec_sbm4__16_ );
    spec_sbm4__06_ = muffin::inject( hif_fault_node.instance, 198ULL, 1ULL, spec_sbm4__05_
             && spec_sbm4__36_ );
    spec_sbm4__14_ = muffin::inject( hif_fault_node.instance, 199ULL, 1ULL, spec_sbm4__08_
             && spec_sbm4__35_ );
    spec_sbm4__32_ = muffin::inject( hif_fault_node.instance, 200ULL, 1ULL, spec_sbm4__30_
             && spec_sbm4__31_ );
    spec_sbm4__00_ = muffin::inject( hif_fault_node.instance, 201ULL, 1ULL, spec_sbm4__35_
             && spec_sbm4__36_ );
    spec_sbm4__11_ = muffin::inject( hif_fault_node.instance, 202ULL, 1ULL, spec_sbm4__05_
             && spec_sbm4__08_ );
    spec_sbm4__07_ = muffin::inject( hif_fault_node.instance, 203ULL, 1ULL, !spec_sbm4__06_
         );
    spec_sbm4__18_ = muffin::inject( hif_fault_node.instance, 204ULL, 1ULL, !spec_sbm4__17_
         );
    spec_sbm4__15_ = muffin::inject( hif_fault_node.instance, 205ULL, 1ULL, !spec_sbm4__14_
         );
    spec_sbm4__33_ = muffin::inject( hif_fault_node.instance, 206ULL, 1ULL, hif_a2t_data.a_5_0
             && spec_sbm4__32_ );
    spec_sbm4__01_ = muffin::inject( hif_fault_node.instance, 207ULL, 1ULL, !spec_sbm4__00_
         );
    spec_sbm4__19_ = muffin::inject( hif_fault_node.instance, 208ULL, 1ULL, spec_sbm4__01_
             && spec_sbm4__07_ );
    spec_sbm4__12_ = muffin::inject( hif_fault_node.instance, 209ULL, 1ULL, !spec_sbm4__11_
         );
    spec_sbm4__34_ = muffin::inject( hif_fault_node.instance, 210ULL, 1ULL, !spec_sbm4__33_
         );
    spec_sbm4__21_ = muffin::inject( hif_fault_node.instance, 211ULL, 1ULL, spec_sbm4__15_
             && spec_sbm4__18_ );
    spec_sbm4__20_ = muffin::inject( hif_fault_node.instance, 212ULL, 1ULL, spec_sbm4__19_
             && spec_sbm4__34_ );
    spec_sbm4__22_ = muffin::inject( hif_fault_node.instance, 213ULL, 1ULL, spec_sbm4__12_
             && spec_sbm4__21_ );
    spec_sbm4__23_ = muffin::inject( hif_fault_node.instance, 214ULL, 1ULL, spec_sbm4__20_
             && spec_sbm4__22_ );
    spec_sbm4__24_ = muffin::inject( hif_fault_node.instance, 215ULL, 1ULL, !spec_sbm4__23_
         );
}


void test::hif_cone_spec_sbm4__29_()
{
    spec_sbm4__13_ = muffin::inject( hif_fault_node.instance, 216ULL, 1ULL, !hif_a2t_data.a_5_0
         );
    spec_sbm4__30_ = muffin::inject( hif_fault_node.instance, 217ULL, 1ULL, !spec_sbm4__37_
         );
    spec_sbm4__31_ = muffin::inject( hif_fault_node.instance, 218ULL, 1ULL, !c_5_0_old
         );
    spec_sbm4__08_ = muffin::inject( hif_fault_node.instance, 219ULL, 1ULL, c_5_0_old
             && spec_sbm4__30_ );
    spec_sbm4__05_ = muffin::inject( hif_fault_node.instance, 220ULL, 1ULL, hif_a2t_data.a_5_1
             && spec_sbm4__13_ );
    spec_sbm4__36_ = muffin::inject( hif_fault_node.instance, 221ULL, 1ULL, spec_sbm4__31_
             && spec_sbm4__37_ );
    spec_sbm4__06_ = muffin::inject( hif_fault_node.instance, 222ULL, 1ULL, spec_sbm4__05_
             && spec_sbm4__36_ );
    spec_sbm4__02_ = muffin::inject( hif_fault_node.instance, 223ULL, 1ULL, hif_a2t_data.a_5_0
             && hif_a2t_data.a_5_1 );
    spec_sbm4__09_ = muffin::inject( hif_fault_node.instance, 224ULL, 1ULL, spec_sbm4__02_
             && spec_sbm4__08_ );
    spec_sbm4__11_ = muffin::inject( hif_fault_node.instance, 225ULL, 1ULL, spec_sbm4__05_
             && spec_sbm4__08_ );
    spec_sbm4__07_ = muffin::inject( hif_fault_node.instance, 226ULL, 1ULL, !spec_sbm4__06_
         );
    spec_sbm4__03_ = muffin::inject( hif_fault_node.instance, 227ULL, 1ULL, spec_sbm4__02_
             && spec_sbm4__36_ );
    spec_sbm4__10_ = muffin::inject( hif_fault_node.instance, 228ULL, 1ULL, !spec_sbm4__09_
         );
    spec_sbm4__04_ = muffin::inject( hif_fault_node.instance, 229ULL, 1ULL, !spec_sbm4__03_
         );
    spec_sbm4__12_ = muffin::inject( hif_fault_node.instance, 230ULL, 1ULL, !spec_sbm4__11_
         );
    spec_sbm4__26_ = muffin::inject( hif_fault_node.instance, 231ULL, 1ULL, spec_sbm4__04_
             && spec_sbm4__07_ );
    spec_sbm4__27_ = muffin::inject( hif_fault_node.instance, 232ULL, 1ULL, spec_sbm4__10_
             && spec_sbm4__12_ );
    spec_sbm4__28_ = muffin::inject( hif_fault_node.instance, 233ULL, 1ULL, spec_sbm4__26_
             && spec_sbm4__27_ );
    spec_sbm4__29_ = muffin::inject( hif_fault_node.instance, 234ULL, 1ULL, !spec_sbm4__28_
         );
}


void test::hif_cone_spec_sbm5__24_()
{
    spec_sbm5__25_ = muffin::inject( hif_fault_node.instance, 235ULL, 1ULL, !hif_a2t_data.a_6_1
         );
    spec_sbm5__13_ = muffin::inject( hif_fault_node.instance, 236ULL, 1ULL, !hif_a2t_data.a_6_0
         );
    spec_sbm5__30_ = muffin::inject( hif_fault_node.instance, 237ULL, 1ULL, !spec_sbm5__37_
         );
    spec_sbm5__31_ = muffin::inject( hif_fault_node.instance, 238ULL, 1ULL, !c_6_0_old
         );
    spec_sbm5__16_ = muffin::inject( hif_fault_node.instance, 239ULL, 1ULL, c_6_0_old
             && spec_sbm5__37_ );
    spec_sbm5__05_ = muffin::inject( hif_fault_node.instance, 240ULL, 1ULL, hif_a2t_data.a_6_1
             && spec_sbm5__13_ );
    spec_sbm5__08_ = muffin::inject( hif_fault_node.instance, 241ULL, 1ULL, c_6_0_old
             && spec_sbm5__30_ );
    spec_sbm5__36_ = muffin::inject( hif_fault_node.instance, 242ULL, 1ULL, spec_sbm5__31_
             && spec_sbm5__37_ );
    spec_sbm5__35_ = muffin::inject( hif_fault_node.instance, 243ULL, 1ULL, hif_a2t_data.a_6_0
             && spec_sbm5__25_ );
    spec_sbm5__17_ = muffin::inject( hif_fault_node.instance, 244ULL, 1ULL, hif_a2t_data.a_6_0
             && spec_sbm5__16_ );
    spec_sbm5__00_ = muffin::inject( hif_fault_node.instance, 245ULL, 1ULL, spec_sbm5__35_
             && spec_sbm5__36_ );
    spec_sbm5__06_ = muffin::inject( hif_fault_node.instance, 246ULL, 1ULL, spec_sbm5__05_
             && spec_sbm5__36_ );
    spec_sbm5__14_ = muffin::inject( hif_fault_node.instance, 247ULL, 1ULL, spec_sbm5__08_
             && spec_sbm5__35_ );
    spec_sbm5__32_ = muffin::inject( hif_fault_node.instance, 248ULL, 1ULL, spec_sbm5__30_
             && spec_sbm5__31_ );
    spec_sbm5__11_ = muffin::inject( hif_fault_node.instance, 249ULL, 1ULL, spec_sbm5__05_
             && spec_sbm5__08_ );
    spec_sbm5__07_ = muffin::inject( hif_fault_node.instance, 250ULL, 1ULL, !spec_sbm5__06_
         );
    spec_sbm5__01_ = muffin::inject( hif_fault_node.instance, 251ULL, 1ULL, !spec_sbm5__00_
         );
    spec_sbm5__15_ = muffin::inject( hif_fault_node.instance, 252ULL, 1ULL, !spec_sbm5__14_
         );
    spec_sbm5__18_ = muffin::inject( hif_fault_node.instance, 253ULL, 1ULL, !spec_sbm5__17_
         );
    spec_sbm5__33_ = muffin::inject( hif_fault_node.instance, 254ULL, 1ULL, hif_a2t_data.a_6_0
             && spec_sbm5__32_ );
    spec_sbm5__12_ = muffin::inject( hif_fault_node.instance, 255ULL, 1ULL, !spec_sbm5__11_
         );
    spec_sbm5__19_ = muffin::inject( hif_fault_node.instance, 256ULL, 1ULL, spec_sbm5__01_
             && spec_sbm5__07_ );
    spec_sbm5__21_ = muffin::inject( hif_fault_node.instance, 257ULL, 1ULL, spec_sbm5__15_
             && spec_sbm5__18_ );
    spec_sbm5__34_ = muffin::inject( hif_fault_node.instance, 258ULL, 1ULL, !spec_sbm5__33_
         );
    spec_sbm5__20_ = muffin::inject( hif_fault_node.instance, 259ULL, 1ULL, spec_sbm5__19_
             && spec_sbm5__34_ );
    spec_sbm5__22_ = muffin::inject( hif_fault_node.instance, 260ULL, 1ULL, spec_sbm5__12_
             && spec_sbm5__21_ );
    spec_sbm5__23_ = muffin::inject( hif_fault_node.instance, 261ULL, 1ULL, spec_sbm5__20_
             && spec_sbm5__22_ );
    spec_sbm5__24_ = muffin::inject( hif_fault_node.instance, 262ULL, 1ULL, !spec_sbm5__23_
         );
}


void test::hif_cone_spec_sbm5__29_()
{
    spec_sbm5__13_ = muffin::inject( hif_fault_node.instance, 263ULL, 1ULL, !hif_a2t_data.a_6_0
         );
    spec_sbm5__30_ = muffin::inject( hif_fault_node.instance, 264ULL, 1ULL, !spec_sbm5__37_
         );
    spec_sbm5__31_ = muffin::inject( hif_fault_node.instance, 265ULL, 1ULL, !c_6_0_old
         );
    spec_sbm5__05_ = muffin::inject( hif_fault_node.instance, 266ULL, 1ULL, hif_a2t_data.a_6_1
             && spec_sbm5__13_ );
    spec_sbm5__08_ = muffin::inject( hif_fault_node.instance, 267ULL, 1ULL, c_6_0_old
             && spec_sbm5__30_ );
    spec_sbm5__36_ = muffin::inject( hif_fault_node.instance, 268ULL, 1ULL, spec_sbm5__31_
             && spec_sbm5__37_ );
    spec_sbm5__02_ = muffin::inject( hif_fault_node.instance, 269ULL, 1ULL, hif_a2t_data.a_6_0
             && hif_a2t_data.a_6_1 );
    spec_sbm5__06_ = muffin::inject( hif_fault_node.instance, 270ULL, 1ULL, spec_sbm5__05_
             && spec_sbm5__36_ );
    spec_sbm5__03_ = muffin::inject( hif_fault_node.instance, 271ULL, 1ULL, spec_sbm5__02_
             && spec_sbm5__36_ );
    spec_sbm5__11_ = muffin::inject( hif_fault_node.instance, 272ULL, 1ULL, spec_sbm5__05_
             && spec_sbm5__08_ );
    spec_sbm5__07_ = muffin::inject( hif_fault_node.instance, 273ULL, 1ULL, !spec_sbm5__06_
         );
    spec_sbm5__09_ = muffin::inject( hif_fault_node.instance, 274ULL, 1ULL, spec_sbm5__02_
             && spec_sbm5__08_ );
    spec_sbm5__04_ = muffin::inject( hif_fault_node.instance, 275ULL, 1ULL, !spec_sbm5__03_
         );
    spec_sbm5__12_ = muffin::inject( hif_fault_node.instance, 276ULL, 1ULL, !spec_sbm5__11_
         );
    spec_sbm5__10_ = muffin::inject( hif_fault_node.instance, 277ULL, 1ULL, !spec_sbm5__09_
         );
    spec_sbm5__26_ = muffin::inject( hif_fault_node.instance, 278ULL, 1ULL, spec_sbm5__04_
             && spec_sbm5__07_ );
    spec_sbm5__27_ = muffin::inject( hif_fault_node.instance, 279ULL, 1ULL, spec_sbm5__10_
             && spec_sbm5__12_ );
    spec_sbm5__28_ = muffin::inject( hif_fault_node.instance, 280ULL, 1ULL, spec_sbm5__26_
             && spec_sbm5__27_ );
    spec_sbm5__29_ = muffin::inject( hif_fault_node.instance, 281ULL, 1ULL, !spec_sbm5__28_
         );
}


void test::hif_cone_spec_sbm6__24_()
{
    spec_sbm6__13_ = muffin::inject( hif_fault_node.instance, 282ULL, 1ULL, !hif_a2t_data.a_7_0
         );
    spec_sbm6__25_ = muffin::inject( hif_fault_node.instance, 283ULL, 1ULL, !hif_a2t_data.a_7_1
         );
    spec_sbm6__30_ = muffin::inject( hif_fault_node.instance, 284ULL, 1ULL, !spec_sbm6__37_
         );
    spec_sbm6__31_ = muffin::inject( hif_fault_node.instance, 285ULL, 1ULL, !c_7_0_old
         );
    spec_sbm6__05_ = muffin::inject( hif_fault_node.instance, 286ULL, 1ULL, hif_a2t_data.a_7_1
             && spec_sbm6__13_ );
    spec_sbm6__08_ = muffin::inject( hif_fault_node.instance, 287ULL, 1ULL, c_7_0_old
             && spec_sbm6__30_ );
    spec_sbm6__16_ = muffin::inject( hif_fault_node.instance, 288ULL, 1ULL, c_7_0_old
             && spec_sbm6__37_ );
    spec_sbm6__35_ = muffin::inject( hif_fault_node.instance, 289ULL, 1ULL, hif_a2t_data.a_7_0
             && spec_sbm6__25_ );
    spec_sbm6__36_ = muffin::inject( hif_fault_node.instance, 290ULL, 1ULL, spec_sbm6__31_
             && spec_sbm6__37_ );
    spec_sbm6__06_ = muffin::inject( hif_fault_node.instance, 291ULL, 1ULL, spec_sbm6__05_
             && spec_sbm6__36_ );
    spec_sbm6__14_ = muffin::inject( hif_fault_node.instance, 292ULL, 1ULL, spec_sbm6__08_
             && spec_sbm6__35_ );
    spec_sbm6__17_ = muffin::inject( hif_fault_node.instance, 293ULL, 1ULL, hif_a2t_data.a_7_0
             && spec_sbm6__16_ );
    spec_sbm6__32_ = muffin::inject( hif_fault_node.instance, 294ULL, 1ULL, spec_sbm6__30_
             && spec_sbm6__31_ );
    spec_sbm6__00_ = muffin::inject( hif_fault_node.instance, 295ULL, 1ULL, spec_sbm6__35_
             && spec_sbm6__36_ );
    spec_sbm6__11_ = muffin::inject( hif_fault_node.instance, 296ULL, 1ULL, spec_sbm6__05_
             && spec_sbm6__08_ );
    spec_sbm6__07_ = muffin::inject( hif_fault_node.instance, 297ULL, 1ULL, !spec_sbm6__06_
         );
    spec_sbm6__18_ = muffin::inject( hif_fault_node.instance, 298ULL, 1ULL, !spec_sbm6__17_
         );
    spec_sbm6__15_ = muffin::inject( hif_fault_node.instance, 299ULL, 1ULL, !spec_sbm6__14_
         );
    spec_sbm6__33_ = muffin::inject( hif_fault_node.instance, 300ULL, 1ULL, hif_a2t_data.a_7_0
             && spec_sbm6__32_ );
    spec_sbm6__01_ = muffin::inject( hif_fault_node.instance, 301ULL, 1ULL, !spec_sbm6__00_
         );
    spec_sbm6__19_ = muffin::inject( hif_fault_node.instance, 302ULL, 1ULL, spec_sbm6__01_
             && spec_sbm6__07_ );
    spec_sbm6__12_ = muffin::inject( hif_fault_node.instance, 303ULL, 1ULL, !spec_sbm6__11_
         );
    spec_sbm6__21_ = muffin::inject( hif_fault_node.instance, 304ULL, 1ULL, spec_sbm6__15_
             && spec_sbm6__18_ );
    spec_sbm6__34_ = muffin::inject( hif_fault_node.instance, 305ULL, 1ULL, !spec_sbm6__33_
         );
    spec_sbm6__20_ = muffin::inject( hif_fault_node.instance, 306ULL, 1ULL, spec_sbm6__19_
             && spec_sbm6__34_ );
    spec_sbm6__22_ = muffin::inject( hif_fault_node.instance, 307ULL, 1ULL, spec_sbm6__12_
             && spec_sbm6__21_ );
    spec_sbm6__23_ = muffin::inject( hif_fault_node.instance, 308ULL, 1ULL, spec_sbm6__20_
             && spec_sbm6__22_ );
    spec_sbm6__24_ = muffin::inject( hif_fault_node.instance, 309ULL, 1ULL, !spec_sbm6__23_
         );
}


void test::hif_cone_spec_sbm6__29_()
{
    spec_sbm6__13_ = muffin::inject( hif_fault_node.instance, 310ULL, 1ULL, !hif_a2t_data.a_7_0
         );
    spec_sbm6__30_ = muffin::inject( hif_fault_node.instance, 311ULL, 1ULL, !spec_sbm6__37_
         );
    spec_sbm6__31_ = muffin::inject( hif_fault_node.instance, 312ULL, 1ULL, !c_7_0_old
         );
    spec_sbm6__05_ = muffin::inject( hif_fault_node.instance, 313ULL, 1ULL, hif_a2t_data.a_7_1
             && spec_sbm6__13_ );
    spec_sbm6__08_ = muffin::inject( hif_fault_node.instance, 314ULL, 1ULL, c_7_0_old
             && spec_sbm6__30_ );
    spec_sbm6__36_ = muffin::inject( hif_fault_node.instance, 315ULL, 1ULL, spec_sbm6__31_
             && spec_sbm6__37_ );
    spec_sbm6__06_ = muffin::inject( hif_fault_node.instance, 316ULL, 1ULL, spec_sbm6__05_
             && spec_sbm6__36_ );
    spec_sbm6__02_ = muffin::inject( hif_fault_node.instance, 317ULL, 1ULL, hif_a2t_data.a_7_0
             && hif_a2t_data.a_7_1 );
    spec_sbm6__11_ = muffin::inject( hif_fault_node.instance, 318ULL, 1ULL, spec_sbm6__05_
             && spec_sbm6__08_ );
    spec_sbm6__07_ = muffin::inject( hif_fault_node.instance, 319ULL, 1ULL, !spec_sbm6__06_
         );
    spec_sbm6__09_ = muffin::inject( hif_fault_node.instance, 320ULL, 1ULL, spec_sbm6__02_
             && spec_sbm6__08_ );
    spec_sbm6__03_ = muffin::inject( hif_fault_node.instance, 321ULL, 1ULL, spec_sbm6__02_
             && spec_sbm6__36_ );
    spec_sbm6__04_ = muffin::inject( hif_fault_node.instance, 322ULL, 1ULL, !spec_sbm6__03_
         );
    spec_sbm6__10_ = muffin::inject( hif_fault_node.instance, 323ULL, 1ULL, !spec_sbm6__09_
         );
    spec_sbm6__12_ = muffin::inject( hif_fault_node.instance, 324ULL, 1ULL, !spec_sbm6__11_
         );
    spec_sbm6__27_ = muffin::inject( hif_fault_node.instance, 325ULL, 1ULL, spec_sbm6__10_
             && spec_sbm6__12_ );
    spec_sbm6__26_ = muffin::inject( hif_fault_node.instance, 326ULL, 1ULL, spec_sbm6__04_
             && spec_sbm6__07_ );
    spec_sbm6__28_ = muffin::inject( hif_fault_node.instance, 327ULL, 1ULL, spec_sbm6__26_
             && spec_sbm6__27_ );
    spec_sbm6__29_ = muffin::inject( hif_fault_node.instance, 328ULL, 1ULL, !spec_sbm6__28_
         );
}


void test::hif_cone_spec_sbm7__24_()
{
    spec_sbm7__30_ = muffin::inject( hif_fault_node.instance, 329ULL, 1ULL, !spec_sbm7__37_
         );
    spec_sbm7__13_ = muffin::inject( hif_fault_node.instance, 330ULL, 1ULL, !hif_a2t_data.a_8_0
         );
    spec_sbm7__25_ = muffin::inject( hif_fault_node.instance, 331ULL, 1ULL, !hif_a2t_data.a_8_1
         );
    spec_sbm7__31_ = muffin::inject( hif_fault_node.instance, 332ULL, 1ULL, !c_8_0_old
         );
    spec_sbm7__05_ = muffin::inject( hif_fault_node.instance, 333ULL, 1ULL, hif_a2t_data.a_8_1
             && spec_sbm7__13_ );
    spec_sbm7__08_ = muffin::inject( hif_fault_node.instance, 334ULL, 1ULL, c_8_0_old
             && spec_sbm7__30_ );
    spec_sbm7__16_ = muffin::inject( hif_fault_node.instance, 335ULL, 1ULL, c_8_0_old
             && spec_sbm7__37_ );
    spec_sbm7__35_ = muffin::inject( hif_fault_node.instance, 336ULL, 1ULL, hif_a2t_data.a_8_0
             && spec_sbm7__25_ );
    spec_sbm7__36_ = muffin::inject( hif_fault_node.instance, 337ULL, 1ULL, spec_sbm7__31_
             && spec_sbm7__37_ );
    spec_sbm7__00_ = muffin::inject( hif_fault_node.instance, 338ULL, 1ULL, spec_sbm7__35_
             && spec_sbm7__36_ );
    spec_sbm7__06_ = muffin::inject( hif_fault_node.instance, 339ULL, 1ULL, spec_sbm7__05_
             && spec_sbm7__36_ );
    spec_sbm7__14_ = muffin::inject( hif_fault_node.instance, 340ULL, 1ULL, spec_sbm7__08_
             && spec_sbm7__35_ );
    spec_sbm7__17_ = muffin::inject( hif_fault_node.instance, 341ULL, 1ULL, hif_a2t_data.a_8_0
             && spec_sbm7__16_ );
    spec_sbm7__32_ = muffin::inject( hif_fault_node.instance, 342ULL, 1ULL, spec_sbm7__30_
             && spec_sbm7__31_ );
    spec_sbm7__01_ = muffin::inject( hif_fault_node.instance, 343ULL, 1ULL, !spec_sbm7__00_
         );
    spec_sbm7__07_ = muffin::inject( hif_fault_node.instance, 344ULL, 1ULL, !spec_sbm7__06_
         );
    spec_sbm7__15_ = muffin::inject( hif_fault_node.instance, 345ULL, 1ULL, !spec_sbm7__14_
         );
    spec_sbm7__18_ = muffin::inject( hif_fault_node.instance, 346ULL, 1ULL, !spec_sbm7__17_
         );
    spec_sbm7__11_ = muffin::inject( hif_fault_node.instance, 347ULL, 1ULL, spec_sbm7__05_
             && spec_sbm7__08_ );
    spec_sbm7__33_ = muffin::inject( hif_fault_node.instance, 348ULL, 1ULL, hif_a2t_data.a_8_0
             && spec_sbm7__32_ );
    spec_sbm7__12_ = muffin::inject( hif_fault_node.instance, 349ULL, 1ULL, !spec_sbm7__11_
         );
    spec_sbm7__19_ = muffin::inject( hif_fault_node.instance, 350ULL, 1ULL, spec_sbm7__01_
             && spec_sbm7__07_ );
    spec_sbm7__21_ = muffin::inject( hif_fault_node.instance, 351ULL, 1ULL, spec_sbm7__15_
             && spec_sbm7__18_ );
    spec_sbm7__34_ = muffin::inject( hif_fault_node.instance, 352ULL, 1ULL, !spec_sbm7__33_
         );
    spec_sbm7__20_ = muffin::inject( hif_fault_node.instance, 353ULL, 1ULL, spec_sbm7__19_
             && spec_sbm7__34_ );
    spec_sbm7__22_ = muffin::inject( hif_fault_node.instance, 354ULL, 1ULL, spec_sbm7__12_
             && spec_sbm7__21_ );
    spec_sbm7__23_ = muffin::inject( hif_fault_node.instance, 355ULL, 1ULL, spec_sbm7__20_
             && spec_sbm7__22_ );
    spec_sbm7__24_ = muffin::inject( hif_fault_node.instance, 356ULL, 1ULL, !spec_sbm7__23_
         );
}


void test::hif_cone_spec_sbm7__29_()
{
    spec_sbm7__30_ = muffin::inject( hif_fault_node.instance, 357ULL, 1ULL, !spec_sbm7__37_
         );
    spec_sbm7__13_ = muffin::inject( hif_fault_node.instance, 358ULL, 1ULL, !hif_a2t_data.a_8_0
         );
    spec_sbm7__31_ = muffin::inject( hif_fault_node.instance, 359ULL, 1ULL, !c_8_0_old
         );
    spec_sbm7__05_ = muffin::inject( hif_fault_node.instance, 360ULL, 1ULL, hif_a2t_data.a_8_1
             && spec_sbm7__13_ );
    spec_sbm7__08_ = muffin::inject( hif_fault_node.instance, 361ULL, 1ULL, c_8_0_old
             && spec_sbm7__30_ );
    spec_sbm7__36_ = muffin::inject( hif_fault_node.instance, 362ULL, 1ULL, spec_sbm7__31_
             && spec_sbm7__37_ );
    spec_sbm7__02_ = muffin::inject( hif_fault_node.instance, 363ULL, 1ULL, hif_a2t_data.a_8_0
             && hif_a2t_data.a_8_1 );
    spec_sbm7__06_ = muffin::inject( hif_fault_node.instance, 364ULL, 1ULL, spec_sbm7__05_
             && spec_sbm7__36_ );
    spec_sbm7__03_ = muffin::inject( hif_fault_node.instance, 365ULL, 1ULL, spec_sbm7__02_
             && spec_sbm7__36_ );
    spec_sbm7__07_ = muffin::inject( hif_fault_node.instance, 366ULL, 1ULL, !spec_sbm7__06_
         );
    spec_sbm7__09_ = muffin::inject( hif_fault_node.instance, 367ULL, 1ULL, spec_sbm7__02_
             && spec_sbm7__08_ );
    spec_sbm7__11_ = muffin::inject( hif_fault_node.instance, 368ULL, 1ULL, spec_sbm7__05_
             && spec_sbm7__08_ );
    spec_sbm7__04_ = muffin::inject( hif_fault_node.instance, 369ULL, 1ULL, !spec_sbm7__03_
         );
    spec_sbm7__10_ = muffin::inject( hif_fault_node.instance, 370ULL, 1ULL, !spec_sbm7__09_
         );
    spec_sbm7__12_ = muffin::inject( hif_fault_node.instance, 371ULL, 1ULL, !spec_sbm7__11_
         );
    spec_sbm7__27_ = muffin::inject( hif_fault_node.instance, 372ULL, 1ULL, spec_sbm7__10_
             && spec_sbm7__12_ );
    spec_sbm7__26_ = muffin::inject( hif_fault_node.instance, 373ULL, 1ULL, spec_sbm7__04_
             && spec_sbm7__07_ );
    spec_sbm7__28_ = muffin::inject( hif_fault_node.instance, 374ULL, 1ULL, spec_sbm7__26_
             && spec_sbm7__27_ );
    spec_sbm7__29_ = muffin::inject( hif_fault_node.instance, 375ULL, 1ULL, !spec_sbm7__28_
         );
}


void test::hif_cone_spec_sbm8__24_()
{
    spec_sbm8__13_ = muffin::inject( hif_fault_node.instance, 376ULL, 1ULL, !hif_a2t_data.a_9_0
         );
    spec_sbm8__25_ = muffin::inject( hif_fault_node.instance, 377ULL, 1ULL, !hif_a2t_data.a_9_1
         );
    spec_sbm8__30_ = muffin::inject( hif_fault_node.instance, 378ULL, 1ULL, !spec_sbm8__37_
         );
    spec_sbm8__31_ = muffin::inject( hif_fault_node.instance, 379ULL, 1ULL, !c_9_0_old
         );
    spec_sbm8__05_ = muffin::inject( hif_fault_node.instance, 380ULL, 1ULL, hif_a2t_data.a_9_1
             && spec_sbm8__13_ );
    spec_sbm8__08_ = muffin::inject( hif_fault_node.instance, 381ULL, 1ULL, c_9_0_old
             && spec_sbm8__30_ );
    spec_sbm8__16_ = muffin::inject( hif_fault_node.instance, 382ULL, 1ULL, c_9_0_old
             && spec_sbm8__37_ );
    spec_sbm8__35_ = muffin::inject( hif_fault_node.instance, 383ULL, 1ULL, hif_a2t_data.a_9_0
             && spec_sbm8__25_ );
    spec_sbm8__36_ = muffin::inject( hif_fault_node.instance, 384ULL, 1ULL, spec_sbm8__31_
             && spec_sbm8__37_ );
    spec_sbm8__00_ = muffin::inject( hif_fault_node.instance, 385ULL, 1ULL, spec_sbm8__35_
             && spec_sbm8__36_ );
    spec_sbm8__06_ = muffin::inject( hif_fault_node.instance, 386ULL, 1ULL, spec_sbm8__05_
             && spec_sbm8__36_ );
    spec_sbm8__14_ = muffin::inject( hif_fault_node.instance, 387ULL, 1ULL, spec_sbm8__08_
             && spec_sbm8__35_ );
    spec_sbm8__17_ = muffin::inject( hif_fault_node.instance, 388ULL, 1ULL, hif_a2t_data.a_9_0
             && spec_sbm8__16_ );
    spec_sbm8__32_ = muffin::inject( hif_fault_node.instance, 389ULL, 1ULL, spec_sbm8__30_
             && spec_sbm8__31_ );
    spec_sbm8__01_ = muffin::inject( hif_fault_node.instance, 390ULL, 1ULL, !spec_sbm8__00_
         );
    spec_sbm8__07_ = muffin::inject( hif_fault_node.instance, 391ULL, 1ULL, !spec_sbm8__06_
         );
    spec_sbm8__11_ = muffin::inject( hif_fault_node.instance, 392ULL, 1ULL, spec_sbm8__05_
             && spec_sbm8__08_ );
    spec_sbm8__15_ = muffin::inject( hif_fault_node.instance, 393ULL, 1ULL, !spec_sbm8__14_
         );
    spec_sbm8__18_ = muffin::inject( hif_fault_node.instance, 394ULL, 1ULL, !spec_sbm8__17_
         );
    spec_sbm8__33_ = muffin::inject( hif_fault_node.instance, 395ULL, 1ULL, hif_a2t_data.a_9_0
             && spec_sbm8__32_ );
    spec_sbm8__12_ = muffin::inject( hif_fault_node.instance, 396ULL, 1ULL, !spec_sbm8__11_
         );
    spec_sbm8__19_ = muffin::inject( hif_fault_node.instance, 397ULL, 1ULL, spec_sbm8__01_
             && spec_sbm8__07_ );
    spec_sbm8__21_ = muffin::inject( hif_fault_node.instance, 398ULL, 1ULL, spec_sbm8__15_
             && spec_sbm8__18_ );
    spec_sbm8__34_ = muffin::inject( hif_fault_node.instance, 399ULL, 1ULL, !spec_sbm8__33_
         );
    spec_sbm8__20_ = muffin::inject( hif_fault_node.instance, 400ULL, 1ULL, spec_sbm8__19_
             && spec_sbm8__34_ );
    spec_sbm8__22_ = muffin::inject( hif_fault_node.instance, 401ULL, 1ULL, spec_sbm8__12_
             && spec_sbm8__21_ );
    spec_sbm8__23_ = muffin::inject( hif_fault_node.instance, 402ULL, 1ULL, spec_sbm8__20_
             && spec_sbm8__22_ );
    spec_sbm8__24_ = muffin::inject( hif_fault_node.instance, 403ULL, 1ULL, !spec_sbm8__23_
         );
}


void test::hif_cone_spec_sbm8__29_()
{
    spec_sbm8__13_ = muffin::inject( hif_fault_node.instance, 404ULL, 1ULL, !hif_a2t_data.a_9_0
         );
    spec_sbm8__30_ = muffin::inject( hif_fault_node.instance, 405ULL, 1ULL, !spec_sbm8__37_
         );
    spec_sbm8__31_ = muffin::inject( hif_fault_node.instance, 406ULL, 1ULL, !c_9_0_old
         );
    spec_sbm8__05_ = muffin::inject( hif_fault_node.instance, 407ULL, 1ULL, hif_a2t_data.a_9_1
             && spec_sbm8__13_ );
    spec_sbm8__08_ = muffin::inject( hif_fault_node.instance, 408ULL, 1ULL, c_9_0_old
             && spec_sbm8__30_ );
    spec_sbm8__36_ = muffin::inject( hif_fault_node.instance, 409ULL, 1ULL, spec_sbm8__31_
             && spec_sbm8__37_ );
    spec_sbm8__02_ = muffin::inject( hif_fault_node.instance, 410ULL, 1ULL, hif_a2t_data.a_9_0
             && hif_a2t_data.a_9_1 );
    spec_sbm8__06_ = muffin::inject( hif_fault_node.instance, 411ULL, 1ULL, spec_sbm8__05_
             && spec_sbm8__36_ );
    spec_sbm8__03_ = muffin::inject( hif_fault_node.instance, 412ULL, 1ULL, spec_sbm8__02_
             && spec_sbm8__36_ );
    spec_sbm8__07_ = muffin::inject( hif_fault_node.instance, 413ULL, 1ULL, !spec_sbm8__06_
         );
    spec_sbm8__09_ = muffin::inject( hif_fault_node.instance, 414ULL, 1ULL, spec_sbm8__02_
             && spec_sbm8__08_ );
    spec_sbm8__11_ = muffin::inject( hif_fault_node.instance, 415ULL, 1ULL, spec_sbm8__05_
             && spec_sbm8__08_ );
    spec_sbm8__04_ = muffin::inject( hif_fault_node.instance, 416ULL, 1ULL, !spec_sbm8__03_
         );
    spec_sbm8__10_ = muffin::inject( hif_fault_node.instance, 417ULL, 1ULL, !spec_sbm8__09_
         );
    spec_sbm8__12_ = muffin::inject( hif_fault_node.instance, 418ULL, 1ULL, !spec_sbm8__11_
         );
    spec_sbm8__26_ = muffin::inject( hif_fault_node.instance, 419ULL, 1ULL, spec_sbm8__04_
             && spec_sbm8__07_ );
    spec_sbm8__27_ = muffin::inject( hif_fault_node.instance, 420ULL, 1ULL, spec_sbm8__10_
             && spec_sbm8__12_ );
    spec_sbm8__28_ = muffin::inject( hif_fault_node.instance, 421ULL, 1ULL, spec_sbm8__26_
             && spec_sbm8__27_ );
    spec_sbm8__29_ = muffin::inject( hif_fault_node.instance, 422ULL, 1ULL, !spec_sbm8__28_
         );
}


void test::hif_cone_spec_sbm9__24_()
{
    spec_sbm9__13_ = muffin::inject( hif_fault_node.instance, 423ULL, 1ULL, !hif_a2t_data.a_10_0
         );
    spec_sbm9__25_ = muffin::inject( hif_fault_node.instance, 424ULL, 1ULL, !hif_a2t_data.a_10_1
         );
    spec_sbm9__30_ = muffin::inject( hif_fault_node.instance, 425ULL, 1ULL, !spec_sbm9__37_
         );
    spec_sbm9__31_ = muffin::inject( hif_fault_node.instance, 426ULL, 1ULL, !c_10_0_old
         );
    spec_sbm9__05_ = muffin::inject( hif_fault_node.instance, 427ULL, 1ULL, hif_a2t_data.a_10_1
             && spec_sbm9__13_ );
    spec_sbm9__08_ = muffin::inject( hif_fault_node.instance, 428ULL, 1ULL, c_10_0_old
             && spec_sbm9__30_ );
    spec_sbm9__16_ = muffin::inject( hif_fault_node.instance, 429ULL, 1ULL, c_10_0_old
             && spec_sbm9__37_ );
    spec_sbm9__35_ = muffin::inject( hif_fault_node.instance, 430ULL, 1ULL, hif_a2t_data.a_10_0
             && spec_sbm9__25_ );
    spec_sbm9__36_ = muffin::inject( hif_fault_node.instance, 431ULL, 1ULL, spec_sbm9__31_
             && spec_sbm9__37_ );
    spec_sbm9__00_ = muffin::inject( hif_fault_node.instance, 432ULL, 1ULL, spec_sbm9__35_
             && spec_sbm9__36_ );
    spec_sbm9__06_ = muffin::inject( hif_fault_node.instance, 433ULL, 1ULL, spec_sbm9__05_
             && spec_sbm9__36_ );
    spec_sbm9__14_ = muffin::inject( hif_fault_node.instance, 434ULL, 1ULL, spec_sbm9__08_
             && spec_sbm9__35_ );
    spec_sbm9__17_ = muffin::inject( hif_fault_node.instance, 435ULL, 1ULL, hif_a2t_data.a_10_0
             && spec_sbm9__16_ );
    spec_sbm9__32_ = muffin::inject( hif_fault_node.instance, 436ULL, 1ULL, spec_sbm9__30_
             && spec_sbm9__31_ );
    spec_sbm9__01_ = muffin::inject( hif_fault_node.instance, 437ULL, 1ULL, !spec_sbm9__00_
         );
    spec_sbm9__07_ = muffin::inject( hif_fault_node.instance, 438ULL, 1ULL, !spec_sbm9__06_
         );
    spec_sbm9__11_ = muffin::inject( hif_fault_node.instance, 439ULL, 1ULL, spec_sbm9__05_
             && spec_sbm9__08_ );
    spec_sbm9__15_ = muffin::inject( hif_fault_node.instance, 440ULL, 1ULL, !spec_sbm9__14_
         );
    spec_sbm9__18_ = muffin::inject( hif_fault_node.instance, 441ULL, 1ULL, !spec_sbm9__17_
         );
    spec_sbm9__33_ = muffin::inject( hif_fault_node.instance, 442ULL, 1ULL, hif_a2t_data.a_10_0
             && spec_sbm9__32_ );
    spec_sbm9__12_ = muffin::inject( hif_fault_node.instance, 443ULL, 1ULL, !spec_sbm9__11_
         );
    spec_sbm9__19_ = muffin::inject( hif_fault_node.instance, 444ULL, 1ULL, spec_sbm9__01_
             && spec_sbm9__07_ );
    spec_sbm9__21_ = muffin::inject( hif_fault_node.instance, 445ULL, 1ULL, spec_sbm9__15_
             && spec_sbm9__18_ );
    spec_sbm9__34_ = muffin::inject( hif_fault_node.instance, 446ULL, 1ULL, !spec_sbm9__33_
         );
    spec_sbm9__20_ = muffin::inject( hif_fault_node.instance, 447ULL, 1ULL, spec_sbm9__19_
             && spec_sbm9__34_ );
    spec_sbm9__22_ = muffin::inject( hif_fault_node.instance, 448ULL, 1ULL, spec_sbm9__12_
             && spec_sbm9__21_ );
    spec_sbm9__23_ = muffin::inject( hif_fault_node.instance, 449ULL, 1ULL, spec_sbm9__20_
             && spec_sbm9__22_ );
    spec_sbm9__24_ = muffin::inject( hif_fault_node.instance, 450ULL, 1ULL, !spec_sbm9__23_
         );
}


void test::hif_cone_spec_sbm9__29_()
{
    spec_sbm9__13_ = muffin::inject( hif_fault_node.instance, 451ULL, 1ULL, !hif_a2t_data.a_10_0
         );
    spec_sbm9__30_ = muffin::inject( hif_fault_node.instance, 452ULL, 1ULL, !spec_sbm9__37_
         );
    spec_sbm9__31_ = muffin::inject( hif_fault_node.instance, 453ULL, 1ULL, !c_10_0_old
         );
    spec_sbm9__05_ = muffin::inject( hif_fault_node.instance, 454ULL, 1ULL, hif_a2t_data.a_10_1
             && spec_sbm9__13_ );
    spec_sbm9__08_ = muffin::inject( hif_fault_node.instance, 455ULL, 1ULL, c_10_0_old
             && spec_sbm9__30_ );
    spec_sbm9__36_ = muffin::inject( hif_fault_node.instance, 456ULL, 1ULL, spec_sbm9__31_
             && spec_sbm9__37_ );
    spec_sbm9__02_ = muffin::inject( hif_fault_node.instance, 457ULL, 1ULL, hif_a2t_data.a_10_0
             && hif_a2t_data.a_10_1 );
    spec_sbm9__06_ = muffin::inject( hif_fault_node.instance, 458ULL, 1ULL, spec_sbm9__05_
             && spec_sbm9__36_ );
    spec_sbm9__03_ = muffin::inject( hif_fault_node.instance, 459ULL, 1ULL, spec_sbm9__02_
             && spec_sbm9__36_ );
    spec_sbm9__07_ = muffin::inject( hif_fault_node.instance, 460ULL, 1ULL, !spec_sbm9__06_
         );
    spec_sbm9__09_ = muffin::inject( hif_fault_node.instance, 461ULL, 1ULL, spec_sbm9__02_
             && spec_sbm9__08_ );
    spec_sbm9__11_ = muffin::inject( hif_fault_node.instance, 462ULL, 1ULL, spec_sbm9__05_
             && spec_sbm9__08_ );
    spec_sbm9__04_ = muffin::inject( hif_fault_node.instance, 463ULL, 1ULL, !spec_sbm9__03_
         );
    spec_sbm9__10_ = muffin::inject( hif_fault_node.instance, 464ULL, 1ULL, !spec_sbm9__09_
         );
    spec_sbm9__12_ = muffin::inject( hif_fault_node.instance, 465ULL, 1ULL, !spec_sbm9__11_
         );
    spec_sbm9__26_ = muffin::inject( hif_fault_node.instance, 466ULL, 1ULL, spec_sbm9__04_
             && spec_sbm9__07_ );
    spec_sbm9__27_ = muffin::inject( hif_fault_node.instance, 467ULL, 1ULL, spec_sbm9__10_
             && spec_sbm9__12_ );
    spec_sbm9__28_ = muffin::inject( hif_fault_node.instance, 468ULL, 1ULL, spec_sbm9__26_
             && spec_sbm9__27_ );
    spec_sbm9__29_ = muffin::inject( hif_fault_node.instance, 469ULL, 1ULL, !spec_sbm9__28_
         );
}



test::test() :
    hif_fault_node(muffin::hif_next_instance_counter(), 480ULL),
    c_10_0_old(false),
    c_9_0_old(false),
    c_8_0_old(false),
    c_7_0_old(false),
    c_6_0_old(false),
    c_5_0_old(false),
    c_4_0_old(false),
    c_3_0_old(false),
    c_2_0_old(false),
    c_1_0_old(false),
    a_10_1_old(false),
    a_10_0_old(false),
    a_9_1_old(false),
    a_9_0_old(false),
    a_8_1_old(false),
    a_8_0_old(false),
    a_7_1_old(false),
    a_7_0_old(false),
    a_6_1_old(false),
    a_6_0_old(false),
    a_5_1_old(false),
    a_5_0_old(false),
    a_4_1_old(false),
    a_4_0_old(false),
    a_3_1_old(false),
    a_3_0_old(false),
    a_2_1_old(false),
    a_2_0_old(false),
    a_1_1_old(false),
    a_1_0_old(false),
    clock_old(false),
    hif_a2t_data(
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false,
    false),
    spec_sbm0__00_(false),
    spec_sbm0__01_(false),
    spec_sbm0__02_(false),
    spec_sbm0__03_(false),
    spec_sbm0__04_(false),
    spec_sbm0__05_(false),
    spec_sbm0__06_(false),
    spec_sbm0__07_(false),
    spec_sbm0__08_(false),
    spec_sbm0__09_(false),
    spec_sbm0__10_(false),
    spec_sbm0__11_(false),
    spec_sbm0__12_(false),
    spec_sbm0__13_(false),
    spec_sbm0__14_(false),
    spec_sbm0__15_(false),
    spec_sbm0__16_(false),
    spec_sbm0__17_(false),
    spec_sbm0__18_(false),
    spec_sbm0__19_(false),
    spec_sbm0__20_(false),
    spec_sbm0__21_(false),
    spec_sbm0__22_(false),
    spec_sbm0__23_(false),
    spec_sbm0__24_(false),
    spec_sbm0__25_(false),
    spec_sbm0__26_(false),
    spec_sbm0__27_(false),
    spec_sbm0__28_(false),
    spec_sbm0__29_(false),
    spec_sbm0__30_(false),
    spec_sbm0__31_(false),
    spec_sbm0__32_(false),
    spec_sbm0__33_(false),
    spec_sbm0__34_(false),
    spec_sbm0__35_(false),
    spec_sbm0__36_(false),
    spec_sbm0__37_(false),
    spec_sbm1__00_(false),
    spec_sbm1__01_(false),
    spec_sbm1__02_(false),
    spec_sbm1__03_(false),
    spec_sbm1__04_(false),
    spec_sbm1__05_(false),
    spec_sbm1__06_(false),
    spec_sbm1__07_(false),
    spec_sbm1__08_(false),
    spec_sbm1__09_(false),
    spec_sbm1__10_(false),
    spec_sbm1__11_(false),
    spec_sbm1__12_(false),
    spec_sbm1__13_(false),
    spec_sbm1__14_(false),
    spec_sbm1__15_(false),
    spec_sbm1__16_(false),
    spec_sbm1__17_(false),
    spec_sbm1__18_(false),
    spec_sbm1__19_(false),
    spec_sbm1__20_(false),
    spec_sbm1__21_(false),
    spec_sbm1__22_(false),
    spec_sbm1__23_(false),
    spec_sbm1__24_(false),
    spec_sbm1__25_(false),
    spec_sbm1__26_(false),
    spec_sbm1__27_(false),
    spec_sbm1__28_(false),
    spec_sbm1__29_(false),
    spec_sbm1__30_(false),
    spec_sbm1__31_(false),
    spec_sbm1__32_(false),
    spec_sbm1__33_(false),
    spec_sbm1__34_(false),
    spec_sbm1__35_(false),
    spec_sbm1__36_(false),
    spec_sbm1__37_(false),
    spec_sbm3__00_(false),
    spec_sbm3__01_(false),
    spec_sbm3__02_(false),
    spec_sbm3__03_(false),
    spec_sbm3__04_(false),
    spec_sbm3__05_(false),
    spec_sbm3__06_(false),
    spec_sbm3__07_(false),
    spec_sbm3__08_(false),
    spec_sbm3__09_(false),
    spec_sbm3__10_(false),
    spec_sbm3__11_(false),
    spec_sbm3__12_(false),
    spec_sbm3__13_(false),
    spec_sbm3__14_(false),
    spec_sbm3__15_(false),
    spec_sbm3__16_(false),
    spec_sbm3__17_(false),
    spec_sbm3__18_(false),
    spec_sbm3__19_(false),
    spec_sbm3__20_(false),
    spec_sbm3__21_(false),
    spec_sbm3__22_(false),
    spec_sbm3__23_(false),
    spec_sbm3__24_(false),
    spec_sbm3__25_(false),
    spec_sbm3__26_(false),
    spec_sbm3__27_(false),
    spec_sbm3__28_(false),
    spec_sbm3__29_(false),
    spec_sbm3__30_(false),
    spec_sbm3__31_(false),
    spec_sbm3__32_(false),
    spec_sbm3__33_(false),
    spec_sbm3__34_(false),
    spec_sbm3__35_(false),
    spec_sbm3__36_(false),
    spec_sbm3__37_(false),
    spec_sbm2__00_(false),
    spec_sbm2__01_(false),
    spec_sbm2__02_(false),
    spec_sbm2__03_(false),
    spec_sbm2__04_(false),
    spec_sbm2__05_(false),
    spec_sbm2__06_(false),
    spec_sbm2__07_(false),
    spec_sbm2__08_(false),
    spec_sbm2__09_(false),
    spec_sbm2__10_(false),
    spec_sbm2__11_(false),
    spec_sbm2__12_(false),
    spec_sbm2__13_(false),
    spec_sbm2__14_(false),
    spec_sbm2__15_(false),
    spec_sbm2__16_(false),
    spec_sbm2__17_(false),
    spec_sbm2__18_(false),
    spec_sbm2__19_(false),
    spec_sbm2__20_(false),
    spec_sbm2__21_(false),
    spec_sbm2__22_(false),
    spec_sbm2__23_(false),
    spec_sbm2__24_(false),
    spec_sbm2__25_(false),
    spec_sbm2__26_(false),
    spec_sbm2__27_(false),
    spec_sbm2__28_(false),
    spec_sbm2__29_(false),
    spec_sbm2__30_(false),
    spec_sbm2__31_(false),
    spec_sbm2__32_(false),
    spec_sbm2__33_(false),
    spec_sbm2__34_(false),
    spec_sbm2__35_(false),
    spec_sbm2__36_(false),
    spec_sbm2__37_(false),
    spec_sbm4__00_(false),
    spec_sbm4__01_(false),
    spec_sbm4__02_(false),
    spec_sbm4__03_(false),
    spec_sbm4__04_(false),
    spec_sbm4__05_(false),
    spec_sbm4__06_(false),
    spec_sbm4__07_(false),
    spec_sbm4__08_(false),
    spec_sbm4__09_(false),
    spec_sbm4__10_(false),
    spec_sbm4__11_(false),
    spec_sbm4__12_(false),
    spec_sbm4__13_(false),
    spec_sbm4__14_(false),
    spec_sbm4__15_(false),
    spec_sbm4__16_(false),
    spec_sbm4__17_(false),
    spec_sbm4__18_(false),
    spec_sbm4__19_(false),
    spec_sbm4__20_(false),
    spec_sbm4__21_(false),
    spec_sbm4__22_(false),
    spec_sbm4__23_(false),
    spec_sbm4__24_(false),
    spec_sbm4__25_(false),
    spec_sbm4__26_(false),
    spec_sbm4__27_(false),
    spec_sbm4__28_(false),
    spec_sbm4__29_(false),
    spec_sbm4__30_(false),
    spec_sbm4__31_(false),
    spec_sbm4__32_(false),
    spec_sbm4__33_(false),
    spec_sbm4__34_(false),
    spec_sbm4__35_(false),
    spec_sbm4__36_(false),
    spec_sbm4__37_(false),
    spec_sbm6__00_(false),
    spec_sbm6__01_(false),
    spec_sbm6__02_(false),
    spec_sbm6__03_(false),
    spec_sbm6__04_(false),
    spec_sbm6__05_(false),
    spec_sbm6__06_(false),
    spec_sbm6__07_(false),
    spec_sbm6__08_(false),
    spec_sbm6__09_(false),
    spec_sbm6__10_(false),
    spec_sbm6__11_(false),
    spec_sbm6__12_(false),
    spec_sbm6__13_(false),
    spec_sbm6__14_(false),
    spec_sbm6__15_(false),
    spec_sbm6__16_(false),
    spec_sbm6__17_(false),
    spec_sbm6__18_(false),
    spec_sbm6__19_(false),
    spec_sbm6__20_(false),
    spec_sbm6__21_(false),
    spec_sbm6__22_(false),
    spec_sbm6__23_(false),
    spec_sbm6__24_(false),
    spec_sbm6__25_(false),
    spec_sbm6__26_(false),
    spec_sbm6__27_(false),
    spec_sbm6__28_(false),
    spec_sbm6__29_(false),
    spec_sbm6__30_(false),
    spec_sbm6__31_(false),
    spec_sbm6__32_(false),
    spec_sbm6__33_(false),
    spec_sbm6__34_(false),
    spec_sbm6__35_(false),
    spec_sbm6__36_(false),
    spec_sbm6__37_(false),
    spec_sbm5__00_(false),
    spec_sbm5__01_(false),
    spec_sbm5__02_(false),
    spec_sbm5__03_(false),
    spec_sbm5__04_(false),
    spec_sbm5__05_(false),
    spec_sbm5__06_(false),
    spec_sbm5__07_(false),
    spec_sbm5__08_(false),
    spec_sbm5__09_(false),
    spec_sbm5__10_(false),
    spec_sbm5__11_(false),
    spec_sbm5__12_(false),
    spec_sbm5__13_(false),
    spec_sbm5__14_(false),
    spec_sbm5__15_(false),
    spec_sbm5__16_(false),
    spec_sbm5__17_(false),
    spec_sbm5__18_(false),
    spec_sbm5__19_(false),
    spec_sbm5__20_(false),
    spec_sbm5__21_(false),
    spec_sbm5__22_(false),
    spec_sbm5__23_(false),
    spec_sbm5__24_(false),
    spec_sbm5__25_(false),
    spec_sbm5__26_(false),
    spec_sbm5__27_(false),
    spec_sbm5__28_(false),
    spec_sbm5__29_(false),
    spec_sbm5__30_(false),
    spec_sbm5__31_(false),
    spec_sbm5__32_(false),
    spec_sbm5__33_(false),
    spec_sbm5__34_(false),
    spec_sbm5__35_(false),
    spec_sbm5__36_(false),
    spec_sbm5__37_(false),
    spec_sbm7__00_(false),
    spec_sbm7__01_(false),
    spec_sbm7__02_(false),
    spec_sbm7__03_(false),
    spec_sbm7__04_(false),
    spec_sbm7__05_(false),
    spec_sbm7__06_(false),
    spec_sbm7__07_(false),
    spec_sbm7__08_(false),
    spec_sbm7__09_(false),
    spec_sbm7__10_(false),
    spec_sbm7__11_(false),
    spec_sbm7__12_(false),
    spec_sbm7__13_(false),
    spec_sbm7__14_(false),
    spec_sbm7__15_(false),
    spec_sbm7__16_(false),
    spec_sbm7__17_(false),
    spec_sbm7__18_(false),
    spec_sbm7__19_(false),
    spec_sbm7__20_(false),
    spec_sbm7__21_(false),
    spec_sbm7__22_(false),
    spec_sbm7__23_(false),
    spec_sbm7__24_(false),
    spec_sbm7__25_(false),
    spec_sbm7__26_(false),
    spec_sbm7__27_(false),
    spec_sbm7__28_(false),
    spec_sbm7__29_(false),
    spec_sbm7__30_(false),
    spec_sbm7__31_(false),
    spec_sbm7__32_(false),
    spec_sbm7__33_(false),
    spec_sbm7__34_(false),
    spec_sbm7__35_(false),
    spec_sbm7__36_(false),
    spec_sbm7__37_(false),
    spec_sbm8__00_(false),
    spec_sbm8__01_(false),
    spec_sbm8__02_(false),
    spec_sbm8__03_(false),
    spec_sbm8__04_(false),
    spec_sbm8__05_(false),
    spec_sbm8__06_(false),
    spec_sbm8__07_(false),
    spec_sbm8__08_(false),
    spec_sbm8__09_(false),
    spec_sbm8__10_(false),
    spec_sbm8__11_(false),
    spec_sbm8__12_(false),
    spec_sbm8__13_(false),
    spec_sbm8__14_(false),
    spec_sbm8__15_(false),
    spec_sbm8__16_(false),
    spec_sbm8__17_(false),
    spec_sbm8__18_(false),
    spec_sbm8__19_(false),
    spec_sbm8__20_(false),
    spec_sbm8__21_(false),
    spec_sbm8__22_(false),
    spec_sbm8__23_(false),
    spec_sbm8__24_(false),
    spec_sbm8__25_(false),
    spec_sbm8__26_(false),
    spec_sbm8__27_(false),
    spec_sbm8__28_(false),
    spec_sbm8__29_(false),
    spec_sbm8__30_(false),
    spec_sbm8__31_(false),
    spec_sbm8__32_(false),
    spec_sbm8__33_(false),
    spec_sbm8__34_(false),
    spec_sbm8__35_(false),
    spec_sbm8__36_(false),
    spec_sbm8__37_(false),
    spec_sbm9__00_(false),
    spec_sbm9__01_(false),
    spec_sbm9__02_(false),
    spec_sbm9__03_(false),
    spec_sbm9__04_(false),
    spec_sbm9__05_(false),
    spec_sbm9__06_(false),
    spec_sbm9__07_(false),
    spec_sbm9__08_(false),
    spec_sbm9__09_(false),
    spec_sbm9__10_(false),
    spec_sbm9__11_(false),
    spec_sbm9__12_(false),
    spec_sbm9__13_(false),
    spec_sbm9__14_(false),
    spec_sbm9__15_(false),
    spec_sbm9__16_(false),
    spec_sbm9__17_(false),
    spec_sbm9__18_(false),
    spec_sbm9__19_(false),
    spec_sbm9__20_(false),
    spec_sbm9__21_(false),
    spec_sbm9__22_(false),
    spec_sbm9__23_(false),
    spec_sbm9__24_(false),
    spec_sbm9__25_(false),
    spec_sbm9__26_(false),
    spec_sbm9__27_(false),
    spec_sbm9__28_(false),
    spec_sbm9__29_(false),
    spec_sbm9__30_(false),
    spec_sbm9__31_(false),
    spec_sbm9__32_(false),
    spec_sbm9__33_(false),
    spec_sbm9__34_(false),
    spec_sbm9__35_(false),
    spec_sbm9__36_(false),
    spec_sbm9__37_(false),
    spec_sbm0__37__new(false),
    spec_sbm1__37__new(false),
    spec_sbm3__37__new(false),
    spec_sbm2__37__new(false),
    spec_sbm4__37__new(false),
    spec_sbm6__37__new(false),
    spec_sbm5__37__new(false),
    spec_sbm7__37__new(false),
    spec_sbm8__37__new(false),
    spec_sbm9__37__new(false),
    process_in_queue(false),
    flag_c_1_0(false),
    flag_c_2_0(false),
    flag_c_3_0(false),
    flag_c_4_0(false),
    flag_c_5_0(false),
    flag_c_6_0(false),
    flag_c_7_0(false),
    flag_c_8_0(false),
    flag_c_9_0(false),
    flag_c_10_0(false),
    flag_spec_sbm0_process_spec_sbm0_process_0_spec_sbm1_process_1_spec_sbm1_process_2_spec_sbm3_process_5_spec_sbm3_process_6_spec_sbm2_process_3_spec_sbm2_process_4_spec_sbm4_process_7_spec_sbm4_process_8_spec_sbm6_process_11_spec_sbm6_process_12_spec_sbm5_process_9_spec_sbm5_process_10_spec_sbm7_process_13_spec_sbm7_process_14_spec_sbm8_process_15_spec_sbm8_process_16_spec_sbm9_process_17_spec_sbm9_process_18_executed
        (false),
    flag_pos_clock(false)
{
    if (hif_fault_list_root != nullptr)
    {
        hif_fault_list_root->prev = &hif_fault_node;
        hif_fault_node.next = hif_fault_list_root;
    }
    hif_fault_list_root = &hif_fault_node;
}


test::~test()
{}


void test::globact_process()
{
    hif_a2t_data.c_1_1 = muffin::inject( hif_fault_node.instance, 470ULL, 1ULL,
             c_1_0_old );
}


void test::globact_process_0()
{
    hif_a2t_data.c_2_1 = muffin::inject( hif_fault_node.instance, 471ULL, 1ULL,
             c_2_0_old );
}


void test::globact_process_1()
{
    hif_a2t_data.c_3_1 = muffin::inject( hif_fault_node.instance, 472ULL, 1ULL,
             c_3_0_old );
}


void test::globact_process_2()
{
    hif_a2t_data.c_4_1 = muffin::inject( hif_fault_node.instance, 473ULL, 1ULL,
             c_4_0_old );
}


void test::globact_process_3()
{
    hif_a2t_data.c_5_1 = muffin::inject( hif_fault_node.instance, 474ULL, 1ULL,
             c_5_0_old );
}


void test::globact_process_4()
{
    hif_a2t_data.c_6_1 = muffin::inject( hif_fault_node.instance, 475ULL, 1ULL,
             c_6_0_old );
}


void test::globact_process_5()
{
    hif_a2t_data.c_7_1 = muffin::inject( hif_fault_node.instance, 476ULL, 1ULL,
             c_7_0_old );
}


void test::globact_process_6()
{
    hif_a2t_data.c_8_1 = muffin::inject( hif_fault_node.instance, 477ULL, 1ULL,
             c_8_0_old );
}


void test::globact_process_7()
{
    hif_a2t_data.c_9_1 = muffin::inject( hif_fault_node.instance, 478ULL, 1ULL,
             c_9_0_old );
}


void test::globact_process_8()
{
    hif_a2t_data.c_10_1 = muffin::inject( hif_fault_node.instance, 479ULL, 1ULL,
             c_10_0_old );
}


void test::spec_sbm0_process_spec_sbm0_process_0_spec_sbm1_process_1_spec_sbm1_process_2_spec_sbm3_process_5_spec_sbm3_process_6_spec_sbm2_process_3_spec_sbm2_process_4_spec_sbm4_process_7_spec_sbm4_process_8_spec_sbm6_process_11_spec_sbm6_process_12_spec_sbm5_process_9_spec_sbm5_process_10_spec_sbm7_process_13_spec_sbm7_process_14_spec_sbm8_process_15_spec_sbm8_process_16_spec_sbm9_process_17_spec_sbm9_process_18
    ()
{
    hif_cone_spec_sbm0__24_();
    spec_sbm0__37__new = spec_sbm0__24_;
    hif_cone_spec_sbm0__29_();
    hif_a2t_data.c_1_0 = spec_sbm0__29_;
    hif_cone_spec_sbm1__24_();
    spec_sbm1__37__new = spec_sbm1__24_;
    hif_cone_spec_sbm1__29_();
    hif_a2t_data.c_2_0 = spec_sbm1__29_;
    hif_cone_spec_sbm3__24_();
    spec_sbm3__37__new = spec_sbm3__24_;
    hif_cone_spec_sbm3__29_();
    hif_a2t_data.c_4_0 = spec_sbm3__29_;
    hif_cone_spec_sbm2__24_();
    spec_sbm2__37__new = spec_sbm2__24_;
    hif_cone_spec_sbm2__29_();
    hif_a2t_data.c_3_0 = spec_sbm2__29_;
    hif_cone_spec_sbm4__24_();
    spec_sbm4__37__new = spec_sbm4__24_;
    hif_cone_spec_sbm4__29_();
    hif_a2t_data.c_5_0 = spec_sbm4__29_;
    hif_cone_spec_sbm6__24_();
    spec_sbm6__37__new = spec_sbm6__24_;
    hif_cone_spec_sbm6__29_();
    hif_a2t_data.c_7_0 = spec_sbm6__29_;
    hif_cone_spec_sbm5__24_();
    spec_sbm5__37__new = spec_sbm5__24_;
    hif_cone_spec_sbm5__29_();
    hif_a2t_data.c_6_0 = spec_sbm5__29_;
    hif_cone_spec_sbm7__24_();
    spec_sbm7__37__new = spec_sbm7__24_;
    hif_cone_spec_sbm7__29_();
    hif_a2t_data.c_8_0 = spec_sbm7__29_;
    hif_cone_spec_sbm8__24_();
    spec_sbm8__37__new = spec_sbm8__24_;
    hif_cone_spec_sbm8__29_();
    hif_a2t_data.c_9_0 = spec_sbm8__29_;
    hif_cone_spec_sbm9__24_();
    spec_sbm9__37__new = spec_sbm9__24_;
    hif_cone_spec_sbm9__29_();
    hif_a2t_data.c_10_0 = spec_sbm9__29_;
}


void test::update_input_queue( bool synch_phase )
{
    process_in_queue = false;
    if (hif_a2t_data.clock != clock_old)
    {
        clock_old = hif_a2t_data.clock;
        if (hif_a2t_data.clock == true)
        {
            flag_pos_clock = true;
        }
        else
        {
            flag_pos_clock = false;
        }
        process_in_queue = true;
    }
    else
    {
        flag_pos_clock = false;
    }
    a_1_0_old = hif_a2t_data.a_1_0;
    a_1_1_old = hif_a2t_data.a_1_1;
    a_2_0_old = hif_a2t_data.a_2_0;
    a_2_1_old = hif_a2t_data.a_2_1;
    a_3_0_old = hif_a2t_data.a_3_0;
    a_3_1_old = hif_a2t_data.a_3_1;
    a_4_0_old = hif_a2t_data.a_4_0;
    a_4_1_old = hif_a2t_data.a_4_1;
    a_5_0_old = hif_a2t_data.a_5_0;
    a_5_1_old = hif_a2t_data.a_5_1;
    a_6_0_old = hif_a2t_data.a_6_0;
    a_6_1_old = hif_a2t_data.a_6_1;
    a_7_0_old = hif_a2t_data.a_7_0;
    a_7_1_old = hif_a2t_data.a_7_1;
    a_8_0_old = hif_a2t_data.a_8_0;
    a_8_1_old = hif_a2t_data.a_8_1;
    a_9_0_old = hif_a2t_data.a_9_0;
    a_9_1_old = hif_a2t_data.a_9_1;
    a_10_0_old = hif_a2t_data.a_10_0;
    a_10_1_old = hif_a2t_data.a_10_1;
}


void test::update_event_queue()
{
    process_in_queue = false;
    spec_sbm0__37_ = spec_sbm0__37__new;
    spec_sbm1__37_ = spec_sbm1__37__new;
    spec_sbm2__37_ = spec_sbm2__37__new;
    spec_sbm3__37_ = spec_sbm3__37__new;
    spec_sbm4__37_ = spec_sbm4__37__new;
    spec_sbm5__37_ = spec_sbm5__37__new;
    spec_sbm6__37_ = spec_sbm6__37__new;
    spec_sbm7__37_ = spec_sbm7__37__new;
    spec_sbm8__37_ = spec_sbm8__37__new;
    spec_sbm9__37_ = spec_sbm9__37__new;
    if (hif_a2t_data.c_1_0 != c_1_0_old)
    {
        c_1_0_old = hif_a2t_data.c_1_0;
        flag_c_1_0 = true;
        process_in_queue = true;
    }
    else
    {
        flag_c_1_0 = false;
    }
    if (hif_a2t_data.c_2_0 != c_2_0_old)
    {
        c_2_0_old = hif_a2t_data.c_2_0;
        flag_c_2_0 = true;
        process_in_queue = true;
    }
    else
    {
        flag_c_2_0 = false;
    }
    if (hif_a2t_data.c_3_0 != c_3_0_old)
    {
        c_3_0_old = hif_a2t_data.c_3_0;
        flag_c_3_0 = true;
        process_in_queue = true;
    }
    else
    {
        flag_c_3_0 = false;
    }
    if (hif_a2t_data.c_4_0 != c_4_0_old)
    {
        c_4_0_old = hif_a2t_data.c_4_0;
        flag_c_4_0 = true;
        process_in_queue = true;
    }
    else
    {
        flag_c_4_0 = false;
    }
    if (hif_a2t_data.c_5_0 != c_5_0_old)
    {
        c_5_0_old = hif_a2t_data.c_5_0;
        flag_c_5_0 = true;
        process_in_queue = true;
    }
    else
    {
        flag_c_5_0 = false;
    }
    if (hif_a2t_data.c_6_0 != c_6_0_old)
    {
        c_6_0_old = hif_a2t_data.c_6_0;
        flag_c_6_0 = true;
        process_in_queue = true;
    }
    else
    {
        flag_c_6_0 = false;
    }
    if (hif_a2t_data.c_7_0 != c_7_0_old)
    {
        c_7_0_old = hif_a2t_data.c_7_0;
        flag_c_7_0 = true;
        process_in_queue = true;
    }
    else
    {
        flag_c_7_0 = false;
    }
    if (hif_a2t_data.c_8_0 != c_8_0_old)
    {
        c_8_0_old = hif_a2t_data.c_8_0;
        flag_c_8_0 = true;
        process_in_queue = true;
    }
    else
    {
        flag_c_8_0 = false;
    }
    if (hif_a2t_data.c_9_0 != c_9_0_old)
    {
        c_9_0_old = hif_a2t_data.c_9_0;
        flag_c_9_0 = true;
        process_in_queue = true;
    }
    else
    {
        flag_c_9_0 = false;
    }
    if (hif_a2t_data.c_10_0 != c_10_0_old)
    {
        c_10_0_old = hif_a2t_data.c_10_0;
        flag_c_10_0 = true;
        process_in_queue = true;
    }
    else
    {
        flag_c_10_0 = false;
    }
}


void test::flag_elaboration()
{
    if (flag_c_1_0)
    {
        globact_process();
    }
    if (flag_c_2_0)
    {
        globact_process_0();
    }
    if (flag_c_3_0)
    {
        globact_process_1();
    }
    if (flag_c_4_0)
    {
        globact_process_2();
    }
    if (flag_c_5_0)
    {
        globact_process_3();
    }
    if (flag_c_6_0)
    {
        globact_process_4();
    }
    if (flag_c_7_0)
    {
        globact_process_5();
    }
    if (flag_c_8_0)
    {
        globact_process_6();
    }
    if (flag_c_9_0)
    {
        globact_process_7();
    }
    if (flag_c_10_0)
    {
        globact_process_8();
    }
    flag_spec_sbm0_process_spec_sbm0_process_0_spec_sbm1_process_1_spec_sbm1_process_2_spec_sbm3_process_5_spec_sbm3_process_6_spec_sbm2_process_3_spec_sbm2_process_4_spec_sbm4_process_7_spec_sbm4_process_8_spec_sbm6_process_11_spec_sbm6_process_12_spec_sbm5_process_9_spec_sbm5_process_10_spec_sbm7_process_13_spec_sbm7_process_14_spec_sbm8_process_15_spec_sbm8_process_16_spec_sbm9_process_17_spec_sbm9_process_18_executed
         = false;
    if (flag_pos_clock)
    {
        spec_sbm0_process_spec_sbm0_process_0_spec_sbm1_process_1_spec_sbm1_process_2_spec_sbm3_process_5_spec_sbm3_process_6_spec_sbm2_process_3_spec_sbm2_process_4_spec_sbm4_process_7_spec_sbm4_process_8_spec_sbm6_process_11_spec_sbm6_process_12_spec_sbm5_process_9_spec_sbm5_process_10_spec_sbm7_process_13_spec_sbm7_process_14_spec_sbm8_process_15_spec_sbm8_process_16_spec_sbm9_process_17_spec_sbm9_process_18
            ();
        flag_spec_sbm0_process_spec_sbm0_process_0_spec_sbm1_process_1_spec_sbm1_process_2_spec_sbm3_process_5_spec_sbm3_process_6_spec_sbm2_process_3_spec_sbm2_process_4_spec_sbm4_process_7_spec_sbm4_process_8_spec_sbm6_process_11_spec_sbm6_process_12_spec_sbm5_process_9_spec_sbm5_process_10_spec_sbm7_process_13_spec_sbm7_process_14_spec_sbm8_process_15_spec_sbm8_process_16_spec_sbm9_process_17_spec_sbm9_process_18_executed
             = true;
    }
}


void test::synch_elaboration()
{
    update_input_queue( true );
    flag_elaboration();
    flag_pos_clock = false;
    update_event_queue();
}


void test::simulate( test_iostruct * io_exchange, int32_t & cycles_number )
{
    hif_a2t_data.clock = io_exchange->clock;
    hif_a2t_data.a_1_0 = io_exchange->a_1_0;
    hif_a2t_data.a_1_1 = io_exchange->a_1_1;
    hif_a2t_data.a_2_0 = io_exchange->a_2_0;
    hif_a2t_data.a_2_1 = io_exchange->a_2_1;
    hif_a2t_data.a_3_0 = io_exchange->a_3_0;
    hif_a2t_data.a_3_1 = io_exchange->a_3_1;
    hif_a2t_data.a_4_0 = io_exchange->a_4_0;
    hif_a2t_data.a_4_1 = io_exchange->a_4_1;
    hif_a2t_data.a_5_0 = io_exchange->a_5_0;
    hif_a2t_data.a_5_1 = io_exchange->a_5_1;
    hif_a2t_data.a_6_0 = io_exchange->a_6_0;
    hif_a2t_data.a_6_1 = io_exchange->a_6_1;
    hif_a2t_data.a_7_0 = io_exchange->a_7_0;
    hif_a2t_data.a_7_1 = io_exchange->a_7_1;
    hif_a2t_data.a_8_0 = io_exchange->a_8_0;
    hif_a2t_data.a_8_1 = io_exchange->a_8_1;
    hif_a2t_data.a_9_0 = io_exchange->a_9_0;
    hif_a2t_data.a_9_1 = io_exchange->a_9_1;
    hif_a2t_data.a_10_0 = io_exchange->a_10_0;
    hif_a2t_data.a_10_1 = io_exchange->a_10_1;
    cycles_number = cycles_number + 1L;
    synch_elaboration();
    while (process_in_queue)
    {
        flag_elaboration();
        update_event_queue();
    }
    io_exchange->c_1_0 = hif_a2t_data.c_1_0;
    io_exchange->c_1_1 = hif_a2t_data.c_1_1;
    io_exchange->c_2_0 = hif_a2t_data.c_2_0;
    io_exchange->c_2_1 = hif_a2t_data.c_2_1;
    io_exchange->c_3_0 = hif_a2t_data.c_3_0;
    io_exchange->c_3_1 = hif_a2t_data.c_3_1;
    io_exchange->c_4_0 = hif_a2t_data.c_4_0;
    io_exchange->c_4_1 = hif_a2t_data.c_4_1;
    io_exchange->c_5_0 = hif_a2t_data.c_5_0;
    io_exchange->c_5_1 = hif_a2t_data.c_5_1;
    io_exchange->c_6_0 = hif_a2t_data.c_6_0;
    io_exchange->c_6_1 = hif_a2t_data.c_6_1;
    io_exchange->c_7_0 = hif_a2t_data.c_7_0;
    io_exchange->c_7_1 = hif_a2t_data.c_7_1;
    io_exchange->c_8_0 = hif_a2t_data.c_8_0;
    io_exchange->c_8_1 = hif_a2t_data.c_8_1;
    io_exchange->c_9_0 = hif_a2t_data.c_9_0;
    io_exchange->c_9_1 = hif_a2t_data.c_9_1;
    io_exchange->c_10_0 = hif_a2t_data.c_10_0;
    io_exchange->c_10_1 = hif_a2t_data.c_10_1;
}


void test::start_of_simulation()
{
    globact_process();
    globact_process_0();
    globact_process_1();
    globact_process_2();
    globact_process_3();
    globact_process_4();
    globact_process_5();
    globact_process_6();
    globact_process_7();
    globact_process_8();
    spec_sbm0_process_spec_sbm0_process_0_spec_sbm1_process_1_spec_sbm1_process_2_spec_sbm3_process_5_spec_sbm3_process_6_spec_sbm2_process_3_spec_sbm2_process_4_spec_sbm4_process_7_spec_sbm4_process_8_spec_sbm6_process_11_spec_sbm6_process_12_spec_sbm5_process_9_spec_sbm5_process_10_spec_sbm7_process_13_spec_sbm7_process_14_spec_sbm8_process_15_spec_sbm8_process_16_spec_sbm9_process_17_spec_sbm9_process_18
        ();
    flag_spec_sbm0_process_spec_sbm0_process_0_spec_sbm1_process_1_spec_sbm1_process_2_spec_sbm3_process_5_spec_sbm3_process_6_spec_sbm2_process_3_spec_sbm2_process_4_spec_sbm4_process_7_spec_sbm4_process_8_spec_sbm6_process_11_spec_sbm6_process_12_spec_sbm5_process_9_spec_sbm5_process_10_spec_sbm7_process_13_spec_sbm7_process_14_spec_sbm8_process_15_spec_sbm8_process_16_spec_sbm9_process_17_spec_sbm9_process_18_executed
         = true;
    update_event_queue();
}


void test::initialize()
{
    start_of_simulation();
}


void test::finalize()
{
}




