/* Generated by Yosys 0.47+149 (git sha1 384c19119, clang++ 18.1.8 -fPIC -O3) */

module spec1(clk, a_1, b_1, c_1, d_1, e_1, f_1);
input clk;
wire clk;
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  input a_1;
  wire a_1;
  input b_1;
  wire b_1;
  input c_1;
  wire c_1;
  input clk;
  wire clk;
  output d_1;
  reg d_1 = 1'h0;
  output e_1;
  wire e_1;
  output f_1;
  wire f_1;
  assign _00_ = c_1 & d_1;
  assign _01_ = _06_ & _00_;
  assign _03_ = _09_ & _02_;
  assign _06_ = a_1 & b_1;
  assign _07_ = c_1 & _05_;
  assign _08_ = _06_ & _07_;
  always @(posedge clk)
    d_1 <= _04_;
  assign _02_ = ~_01_;
  assign _04_ = ~_03_;
  assign _05_ = ~d_1;
  assign _09_ = ~_08_;
  assign e_1 = d_1;
  assign f_1 = d_1;
endmodule
